import React, { useState } from "react";
import { CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Layers, Sparkles, ChevronLeft, ChevronRight, RotateCw, Loader2 } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { Alert, AlertDescription } from "@/components/ui/alert";

export default function FlashcardsTab({ lesson, extractedContent }) {
  const [flashcards, setFlashcards] = useState(null);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerateFlashcards = async () => {
    setIsGenerating(true);
    try {
      // TODO: Implement flashcard generation using Gemini 2.5 Flash
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Placeholder flashcards
      setFlashcards([
        {
          front: "What is the main concept in this course?",
          back: "This flashcard will be generated from your notes using AI. The content will be concise, focused, and designed for effective memorization."
        },
        {
          front: "Key term or question",
          back: "Definition or answer generated by AI based on course material"
        },
        {
          front: "Important concept",
          back: "Detailed explanation from your course notes"
        }
      ]);
      setCurrentIndex(0);
      setIsFlipped(false);
    } catch (error) {
      console.error("Error generating flashcards:", error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleNext = () => {
    if (currentIndex < flashcards.length - 1) {
      setCurrentIndex(prev => prev + 1);
      setIsFlipped(false);
    }
  };

  const handlePrev = () => {
    if (currentIndex > 0) {
      setCurrentIndex(prev => prev - 1);
      setIsFlipped(false);
    }
  };

  const handleFlip = () => {
    setIsFlipped(prev => !prev);
  };

  if (!flashcards) {
    return (
      <div className="flex flex-col h-[calc(100vh-200px)]">
        <CardHeader className="border-b border-purple-200">
          <CardTitle className="text-slate-900 flex items-center gap-2">
            <Layers className="w-5 h-5" />
            AI Flashcards
          </CardTitle>
        </CardHeader>

        <CardContent className="flex-1 flex flex-col items-center justify-center p-6">
          <div className="text-center space-y-6 max-w-md">
            <div className="w-20 h-20 rounded-full bg-purple-100 flex items-center justify-center mx-auto">
              <Layers className="w-10 h-10 text-purple-600" />
            </div>
            <div>
              <h3 className="text-xl font-semibold text-slate-900 mb-2">Generate Smart Flashcards</h3>
              <p className="text-slate-600 text-sm">
                Our AI will create flashcards from your notes to help you memorize key concepts and test your knowledge effectively.
              </p>
            </div>
            <Alert className="max-w-md bg-purple-50 border-purple-200">
              <AlertDescription className="text-xs text-slate-600">
                Flashcards will be generated using Gemini 2.5 Flash based on your notes.
              </AlertDescription>
            </Alert>
            <Button
              onClick={handleGenerateFlashcards}
              disabled={isGenerating}
              className="bg-gradient-to-r from-purple-600 to-yellow-500 hover:from-purple-700 hover:to-yellow-600 text-white"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 mr-2" />
                  Generate Flashcards
                </>
              )}
            </Button>
          </div>
        </CardContent>
      </div>
    );
  }

  const currentCard = flashcards[currentIndex];

  return (
    <div className="flex flex-col h-[calc(100vh-200px)]">
      <CardHeader className="border-b border-purple-200">
        <CardTitle className="text-slate-900 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Layers className="w-5 h-5" />
            Flashcards
          </div>
          <span className="text-sm text-slate-600">
            {currentIndex + 1} / {flashcards.length}
          </span>
        </CardTitle>
      </CardHeader>

      <CardContent className="flex-1 flex flex-col items-center justify-center p-6">
        {/* Flashcard */}
        <div className="w-full max-w-2xl mb-8">
          <div
            onClick={handleFlip}
            className="relative w-full h-80 cursor-pointer perspective-1000"
          >
            <AnimatePresence mode="wait">
              <motion.div
                key={isFlipped ? 'back' : 'front'}
                initial={{ rotateY: 90, opacity: 0 }}
                animate={{ rotateY: 0, opacity: 1 }}
                exit={{ rotateY: -90, opacity: 0 }}
                transition={{ duration: 0.3 }}
                className="absolute inset-0 bg-gradient-to-br from-purple-50 to-white border-2 border-purple-300 rounded-2xl p-8 flex items-center justify-center shadow-xl"
              >
                <div className="text-center">
                  <p className="text-xs text-purple-600 font-semibold mb-4">
                    {isFlipped ? 'Answer' : 'Question'}
                  </p>
                  <p className="text-lg md:text-xl text-slate-900 leading-relaxed">
                    {isFlipped ? currentCard.back : currentCard.front}
                  </p>
                  <p className="text-xs text-slate-600 mt-6">
                    Click to {isFlipped ? 'see question' : 'reveal answer'}
                  </p>
                </div>
              </motion.div>
            </AnimatePresence>
          </div>
        </div>

        {/* Controls */}
        <div className="flex items-center gap-4">
          <Button
            onClick={handlePrev}
            disabled={currentIndex === 0}
            variant="outline"
            className="border-purple-200 text-slate-700"
          >
            <ChevronLeft className="w-4 h-4" />
          </Button>

          <Button
            onClick={handleFlip}
            variant="outline"
            className="border-purple-200 text-slate-700"
          >
            <RotateCw className="w-4 h-4 mr-2" />
            Flip
          </Button>

          <Button
            onClick={handleNext}
            disabled={currentIndex === flashcards.length - 1}
            variant="outline"
            className="border-purple-200 text-slate-700"
          >
            <ChevronRight className="w-4 h-4" />
          </Button>
        </div>

        {/* Progress */}
        <div className="w-full max-w-2xl mt-6">
          <div className="h-1 bg-slate-200 rounded-full overflow-hidden">
            <div
              className="h-full bg-gradient-to-r from-purple-600 to-yellow-500 transition-all duration-300"
              style={{ width: `${((currentIndex + 1) / flashcards.length) * 100}%` }}
            />
          </div>
        </div>
      </CardContent>
    </div>
  );
}