import React, { useState, useEffect, useRef } from "react";
import { base44 } from "@/api/base44Client";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Sparkles, Loader2, RotateCcw, Shuffle, ChevronLeft, ChevronRight, HelpCircle, X, Zap, CheckCircle2, Play, Copy } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { motion, AnimatePresence } from "framer-motion";
import XPGainToast from "@/components/gamification/XPGainToast";
import AskAIButton from "@/components/ai-tutor/AskAIButton";
import { recordDailyActivity, awardDailyXP } from "@/components/utils/dailyReset";
import FlashcardSetsList from "./FlashcardSetsList";
import { useSubscription } from "@/components/subscription/SubscriptionContext";
import { useTheme } from "@/components/theme/ThemeProvider";

export default function FlashcardsTab({ lesson, extractedContent, focusTopics }) {
  const { canDoTask, incrementTaskCount, triggerUpgradeModal } = useSubscription();
  const { isDark } = useTheme();
  const [cards, setCards] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [showHowTo, setShowHowTo] = useState(false);
  const [sessionStats, setSessionStats] = useState({ reviewed: 0, correct: 0 });
  const [xpToast, setXpToast] = useState({ show: false, xp: 0, reason: '' });
  const [streakCount, setStreakCount] = useState(0);
  const [studyPlanTopics, setStudyPlanTopics] = useState(null);
  const [showSetsList, setShowSetsList] = useState(true); // Start with list view

  // Track if we're generating to prevent duplicate calls
  const isGeneratingRef = useRef(false);
  const pendingStudyTaskRef = useRef(null);
  const hasAutoGeneratedRef = useRef(false);

  useEffect(() => {
    if (lesson?.id) {
      loadFlashcards();
    }
    // Don't load study plan topics on mount - only when needed for generation
  }, [lesson?.id]);

  // Listen for study task generation requests - auto-generate when navigating from study plan
  // Use a ref to track if we've already handled this event to prevent duplicates
  const hasHandledStudyTaskRef = useRef(false);
  
  useEffect(() => {
    hasHandledStudyTaskRef.current = false; // Reset when lesson changes
  }, [lesson?.id]);
  
  useEffect(() => {
    const handleStudyTask = async (e) => {
      if (e.detail.taskType === 'flashcards') {
        // Prevent duplicate handling
        if (hasHandledStudyTaskRef.current || isGeneratingRef.current) {
          console.log('🎯 Flashcard event already handled or generating, skipping');
          return;
        }
        hasHandledStudyTaskRef.current = true;
        
        console.log('🎯 Received flashcard generation request from study plan');
        pendingStudyTaskRef.current = e.detail.task;
        
        // Use already loaded cards if available, otherwise check DB
        if (cards && cards.length > 0) {
          console.log('🎯 Cards already loaded, skipping generation');
          return;
        }
        
        // Auto-generate if no cards exist
        if (!isGeneratingRef.current) {
          handleGenerate();
        }
      }
    };
    
    window.addEventListener('generateFromStudyTask', handleStudyTask);
    return () => window.removeEventListener('generateFromStudyTask', handleStudyTask);
  }, [lesson?.id, cards]);
  
  const loadStudyPlanTopics = async () => {
    if (!lesson?.id) return;
    try {
      const plans = await base44.entities.StudyPlan.filter({ 
        lesson_id: lesson.id,
        status: 'active'
      });
      if (plans.length > 0) {
        const flashcardTask = plans[0].tasks?.find(t => t.task_type === 'flashcards' && !t.completed);
        if (flashcardTask?.focus_topics?.length > 0) {
          setStudyPlanTopics(flashcardTask.focus_topics);
        }
      }
    } catch (error) {
      console.error("Error loading study plan topics:", error);
    }
  };

  const loadFlashcards = async () => {
    if (!lesson) return;
    try {
      const existingCards = await base44.entities.Flashcard.filter({ lesson_id: lesson.id });
      if (existingCards.length > 0) {
        setCards(existingCards);
        setShowSetsList(true); // Show list view when cards exist
      }
    } catch (error) {
      console.error("Error loading flashcards:", error);
    }
  };

  const handleGenerate = async () => {
    if (isGeneratingRef.current) return;
    
    // Check subscription limit for flashcard generation
    const taskCheck = await canDoTask();
    if (!taskCheck.allowed) {
      triggerUpgradeModal('tasks');
      return;
    }
    
    isGeneratingRef.current = true;
    setIsGenerating(true);
    
    // Increment task count BEFORE generating
    await incrementTaskCount();
    
    try {
      // Use compressed content if available, otherwise truncate large content
      let contentForFlashcards = lesson.compressed_content || extractedContent || lesson.description || 'General course material';
      if (contentForFlashcards.length > 50000) {
        contentForFlashcards = contentForFlashcards.substring(0, 50000) + "\n...[content truncated]";
      }
      
      // Get focus topics from study plan if available
      const topicsToFocus = focusTopics || studyPlanTopics;
      
      // Use Gemini Flash Lite via backend function
      const { data: response } = await base44.functions.invoke('generateFlashcards', {
        course_name: lesson.course_name,
        content: contentForFlashcards,
        focus_topics: topicsToFocus || []
      });

      const generatedCards = response?.flashcards || [];
      
      // Guard against empty or invalid flashcards array
      if (!Array.isArray(generatedCards) || generatedCards.length === 0) {
        console.error("No flashcards generated");
        setIsGenerating(false);
        return;
      }
      
      // Save cards sequentially to avoid rate limits/502 errors
      const savedCards = [];
      for (const card of generatedCards) {
        let attempts = 0;
        while (attempts < 3) {
          try {
            const saved = await base44.entities.Flashcard.create({
              lesson_id: lesson.id,
              question: card.question || "Question",
              answer: card.answer || "Answer",
              topics: card.topics || [],
              difficulty: card.difficulty || "medium",
              status: "new",
              mastery_level: 0
            });
            savedCards.push(saved);
            break;
          } catch (err) {
            attempts++;
            if (attempts >= 3) throw err;
            await new Promise(r => setTimeout(r, 500 * attempts)); // backoff
          }
        }
      }
      setCards(savedCards);
      pendingStudyTaskRef.current = null;
    } catch (error) {
      console.error("Error generating flashcards:", error);
    }
    setIsGenerating(false);
    isGeneratingRef.current = false;
  };

  const handleFlip = () => {
    setIsFlipped(!isFlipped);
  };

  const awardXP = async (amount, reason) => {
    try {
      // Use centralized XP tracking
      const result = await awardDailyXP(amount, reason);
      if (result.success) {
        // Also record flashcard activity
        await recordDailyActivity('flashcards', 1);
        
        // Update flashcards mastered count
        const user = await base44.auth.me();
        await base44.auth.updateMe({
          total_flashcards_mastered: (user.total_flashcards_mastered || 0) + 1
        });
        
        setXpToast({ show: true, xp: amount, reason });
      }
    } catch (error) {
      console.error("Error awarding XP:", error);
    }
  };

  const handleRating = async (knew) => {
    const currentCard = cards[currentIndex];
    
    // Check subscription limit for tasks (only on first review of a card)
    const wasReviewed = currentCard.review_count > 0;
    if (!wasReviewed) {
      const taskCheck = await canDoTask();
      if (!taskCheck.allowed) {
        triggerUpgradeModal('tasks');
        return;
      }
      await incrementTaskCount();
    }
    
    // Track review count - any review counts as completion
    const newReviewCount = (currentCard.review_count || 0) + 1;
    const newStatus = newReviewCount >= 1 ? 'learning' : 'new';
    
    // Update streak and award XP
    if (knew) {
      const newStreak = streakCount + 1;
      setStreakCount(newStreak);
      
      // Award XP on streak milestones
      if (newStreak >= 5 && newStreak % 5 === 0) {
        awardXP(10, `${newStreak} card streak! 🔥`);
      }
    } else {
      setStreakCount(0);
    }

    try {
      await base44.entities.Flashcard.update(currentCard.id, {
        status: newStatus,
        review_count: newReviewCount,
        last_reviewed: new Date().toISOString()
      });

      const updatedCards = [...cards];
      updatedCards[currentIndex] = { 
        ...currentCard, 
        status: newStatus, 
        review_count: newReviewCount
      };
      setCards(updatedCards);
      
      // Update session stats - only count as reviewed when answered
      setSessionStats(prev => ({
        reviewed: prev.reviewed + 1,
        correct: knew ? prev.correct + 1 : prev.correct
      }));

      // Update study plan with total reviewed count (cards that have been reviewed at least once)
      // First review of a card = 1 completion toward the task
      if (!wasReviewed) {
        const totalReviewed = updatedCards.filter(c => c.review_count > 0).length;
        console.log(`📚 Flashcards: ${totalReviewed} cards reviewed/completed`);
        const taskCompleted = await updateStudyPlanProgress('flashcards', totalReviewed);
        
        // Trigger Polly engine when task completes OR on milestones (every 5 cards)
        if (taskCompleted || totalReviewed % 5 === 0) {
          base44.functions.invoke('runPollyEngine', {
            trigger_event: taskCompleted ? 'task_completed' : 'flashcard_milestone',
            lesson_id: lesson.id
          }).catch(err => console.warn('Polly trigger failed:', err.message));
        }
      }
    } catch (error) {
      console.error("Error updating flashcard:", error);
    }

    // Move to next card
    setIsFlipped(false);
    setTimeout(() => {
      if (currentIndex < cards.length - 1) {
        setCurrentIndex(currentIndex + 1);
      } else {
        setCurrentIndex(0);
      }
    }, 200);
  };

  const updateStudyPlanProgress = async (taskType, completedCount) => {
    // Update study plan with total completed count (cards reviewed at least once)
    // Returns true if task just completed
    try {
      const plans = await base44.entities.StudyPlan.filter({ 
        lesson_id: lesson.id,
        status: 'active'
      });
      if (plans.length === 0) return false;
      
      const plan = plans[0];
      let taskJustCompleted = false;
      
      const updatedTasks = plan.tasks.map(task => {
        if (task.task_type === taskType) {
          const newCount = completedCount;
          const wasComplete = task.completed;
          const targetCount = task.target_count || 10;
          const isComplete = newCount >= targetCount;
          
          // Check if task just became complete
          if (isComplete && !wasComplete) {
            taskJustCompleted = true;
          }
          
          console.log(`📚 Flashcard task update: ${newCount}/${targetCount} completed, task complete: ${isComplete}`);
          
          return {
            ...task,
            completed_count: newCount,
            completed: isComplete,
            completed_date: isComplete && !task.completed_date ? new Date().toISOString() : task.completed_date
          };
        }
        return task;
      });
      
      const allComplete = updatedTasks.every(t => t.completed);
      
      await base44.entities.StudyPlan.update(plan.id, {
        tasks: updatedTasks,
        all_tasks_completed: allComplete,
        official_exam_unlocked: allComplete
      });
      
      return taskJustCompleted;
    } catch (error) {
      console.error("Error updating study plan:", error);
      return false;
    }
  };

  const handleShuffle = () => {
    const shuffled = [...cards].sort(() => Math.random() - 0.5);
    setCards(shuffled);
    setCurrentIndex(0);
    setIsFlipped(false);
  };

  const handlePrev = () => {
    setIsFlipped(false);
    setCurrentIndex(prev => prev > 0 ? prev - 1 : cards.length - 1);
  };

  const handleNext = () => {
    setIsFlipped(false);
    setCurrentIndex(prev => prev < cards.length - 1 ? prev + 1 : 0);
  };

  const handleRegenerate = async () => {
    // Check subscription limit for regeneration
    const taskCheck = await canDoTask();
    if (!taskCheck.allowed) {
      triggerUpgradeModal('tasks');
      return;
    }
    
    // Increment task count BEFORE regenerating
    await incrementTaskCount();
    
    // Delete existing cards
    if (cards && cards.length > 0) {
      await Promise.all(cards.map(c => base44.entities.Flashcard.delete(c.id)));
    }
    setCards(null);
    setCurrentIndex(0);
    setIsFlipped(false);
    setSessionStats({ reviewed: 0, correct: 0 });
  };



  // Show list view when cards exist and showSetsList is true
  if (cards && cards.length > 0 && showSetsList) {
    return (
      <FlashcardSetsList 
        cards={cards}
        onSelectSet={(idx) => {
          setCurrentIndex(idx);
          setIsFlipped(false);
          setShowSetsList(false);
        }}
        onGenerateNew={handleRegenerate}
      />
    );
  }

  // Initial state - not generated - styled like TeachItTab
  if (!cards && !isGenerating) {
    return (
      <div className={`flex items-center justify-center p-4 pb-8 w-full max-w-full ${isDark ? 'bg-[#0a0a12]' : 'bg-slate-50'}`} style={{ boxSizing: 'border-box', overflowX: 'hidden' }}>
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.4 }}
          className="w-full max-w-md"
        >
          <Card className={`backdrop-blur-xl border-2 shadow-2xl overflow-hidden ${isDark ? 'bg-[#12121a]/95 border-purple-500/30' : 'bg-white/95 border-purple-200'}`}>
            <div className="bg-gradient-to-r from-purple-600 via-purple-700 to-purple-800 px-5 py-6 text-center">
              <motion.div
                animate={{ rotate: [0, -10, 10, -10, 0] }}
                transition={{ duration: 0.6, delay: 0.2 }}
              >
                <Sparkles className="w-16 h-16 text-yellow-300 mx-auto mb-3 drop-shadow-lg" />
              </motion.div>
              <h3 className="text-xl font-black text-white mb-1">AI-Powered Flashcards</h3>
              <p className="text-purple-100 text-xs">
                Master concepts through active recall
              </p>
            </div>
            <div className="p-5 text-center w-full" style={{ boxSizing: 'border-box' }}>
              <p className={`mb-4 text-sm leading-relaxed ${isDark ? 'text-slate-300' : 'text-slate-600'}`}>
                Generate smart flashcards from your notes. Think of the answer, then reveal to check yourself!
              </p>
              
              {/* XP incentive */}
              <div className={`rounded-xl p-3 border mb-6 ${isDark ? 'bg-gradient-to-r from-yellow-500/10 to-amber-500/10 border-yellow-500/30' : 'bg-gradient-to-r from-yellow-50 to-amber-50 border-yellow-200'}`}>
                <div className="flex items-center justify-center gap-2">
                  <Zap className={`w-4 h-4 ${isDark ? 'text-yellow-400' : 'text-yellow-600'}`} />
                  <span className={`text-xs font-medium ${isDark ? 'text-yellow-300' : 'text-yellow-800'}`}>
                    Earn <span className="font-bold">+2-10 XP</span> per card mastered!
                  </span>
                </div>
              </div>
              
              <Button
                onClick={handleGenerate}
                className="w-full h-14 bg-gradient-to-r from-purple-600 via-purple-700 to-purple-800 hover:from-purple-700 hover:via-purple-800 hover:to-purple-900 text-white font-bold text-lg rounded-xl shadow-xl"
              >
                <Sparkles className="w-5 h-5 mr-2" />
                Generate Flashcards
              </Button>
            </div>
          </Card>
        </motion.div>
      </div>
    );
  }

  // Loading state
  if (isGenerating) {
    return (
      <Card className={`backdrop-blur-xl border shadow-xl mx-3 p-6 max-w-lg md:mx-auto mb-8 ${isDark ? 'bg-[#12121a]/90 border-purple-500/30' : 'bg-white/90 border-purple-200'}`}>
        <div className="text-center space-y-4">
          <div className="w-16 h-16 bg-gradient-to-br from-purple-500 to-purple-700 rounded-full flex items-center justify-center mx-auto animate-pulse">
            <Sparkles className="w-8 h-8 text-white" />
          </div>
          <div>
            <h3 className={`text-lg font-bold mb-2 ${isDark ? 'text-slate-100' : 'text-slate-900'}`}>Generating Flashcards...</h3>
            <p className={`text-sm ${isDark ? 'text-slate-300' : 'text-slate-600'}`}>
              Creating intelligent flashcards from your course content.
            </p>
          </div>
          <div className="flex justify-center">
            <Loader2 className="w-6 h-6 animate-spin text-purple-600" />
          </div>
        </div>
      </Card>
    );
  }

  if (!cards || cards.length === 0) {
    return (
      <div className={`flex items-center justify-center p-4 pb-8 ${isDark ? 'bg-[#0a0a12]' : 'bg-slate-50'}`}>
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.4 }}
        >
          <Card className={`backdrop-blur-xl border-2 shadow-2xl overflow-hidden max-w-md ${isDark ? 'bg-[#12121a]/95 border-purple-500/30' : 'bg-white/95 border-purple-200'}`}>
            <div className="bg-gradient-to-r from-purple-600 via-purple-700 to-purple-800 px-5 py-6 text-center">
              <Sparkles className="w-16 h-16 text-yellow-300 mx-auto mb-3 drop-shadow-lg" />
              <h3 className="text-xl font-black text-white mb-1">AI-Powered Flashcards</h3>
              <p className="text-purple-100 text-xs">
                Master concepts through active recall
              </p>
            </div>
            <div className="p-5 text-center">
              <p className={`mb-5 text-sm leading-relaxed ${isDark ? 'text-slate-300' : 'text-slate-600'}`}>
                Generate intelligent flashcards from your notes.
              </p>
              <Button
                onClick={handleGenerate}
                className="w-full h-14 bg-gradient-to-r from-purple-600 via-purple-700 to-purple-800 hover:from-purple-700 hover:via-purple-800 hover:to-purple-900 text-white font-bold text-lg rounded-xl shadow-xl"
              >
                <Sparkles className="w-5 h-5 mr-2" />
                Generate Flashcards
              </Button>
            </div>
          </Card>
        </motion.div>
      </div>
    );
  }

  const currentCard = cards[currentIndex];
  const progress = ((currentIndex + 1) / cards.length) * 100;
  const masteredCount = cards.filter(c => c.mastered).length;

  const getDifficultyColor = (difficulty) => {
    switch (difficulty) {
      case "easy": return "bg-emerald-100 text-emerald-700";
      case "hard": return "bg-red-100 text-red-700";
      default: return "bg-amber-100 text-amber-700";
    }
  };

  const getMasteryColor = (level) => {
    if (level >= 4) return "bg-emerald-500";
    if (level >= 2) return "bg-amber-500";
    return "bg-slate-300";
  };

  return (
    <div className={`space-y-3 px-3 py-3 pb-8 w-full max-w-full md:max-w-lg mx-auto ${isDark ? 'bg-[#0a0a12]' : 'bg-slate-50'}`} style={{ boxSizing: 'border-box', overflowX: 'hidden' }}>
      {/* How to use modal */}
      <AnimatePresence>
        {showHowTo && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"
            onClick={() => setShowHowTo(false)}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className={`rounded-2xl max-w-sm w-full p-5 shadow-2xl ${isDark ? 'bg-[#12121a]' : 'bg-white'}`}
              onClick={e => e.stopPropagation()}
            >
              <div className="flex items-center justify-between mb-4">
                <h3 className={`text-lg font-bold ${isDark ? 'text-slate-100' : 'text-slate-900'}`}>How to Use Flashcards</h3>
                <button onClick={() => setShowHowTo(false)} className={`p-1 rounded-full ${isDark ? 'hover:bg-white/10' : 'hover:bg-slate-100'}`}>
                  <X className="w-5 h-5 text-slate-500" />
                </button>
              </div>
              
              <div className="space-y-4">
                <div className="flex gap-3">
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${isDark ? 'bg-purple-600/20' : 'bg-purple-100'}`}>
                    <span className={`font-bold text-sm ${isDark ? 'text-purple-400' : 'text-purple-600'}`}>1</span>
                  </div>
                  <div>
                    <p className={`font-medium text-sm ${isDark ? 'text-slate-200' : 'text-slate-900'}`}>Read the question</p>
                    <p className={`text-xs ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>Think about the answer in your head or say it out loud</p>
                  </div>
                </div>
                
                <div className="flex gap-3">
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${isDark ? 'bg-purple-600/20' : 'bg-purple-100'}`}>
                    <span className={`font-bold text-sm ${isDark ? 'text-purple-400' : 'text-purple-600'}`}>2</span>
                  </div>
                  <div>
                    <p className={`font-medium text-sm ${isDark ? 'text-slate-200' : 'text-slate-900'}`}>Tap to reveal</p>
                    <p className={`text-xs ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>Click anywhere on the card to flip and see the answer</p>
                  </div>
                </div>
                
                <div className="flex gap-3">
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${isDark ? 'bg-purple-600/20' : 'bg-purple-100'}`}>
                    <span className={`font-bold text-sm ${isDark ? 'text-purple-400' : 'text-purple-600'}`}>3</span>
                  </div>
                  <div>
                    <p className={`font-medium text-sm ${isDark ? 'text-slate-200' : 'text-slate-900'}`}>Rate yourself honestly</p>
                    <p className={`text-xs ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>Did you know it? This helps the app show you cards you need to practice more</p>
                  </div>
                </div>

                <div className={`border rounded-xl p-3 mt-4 ${isDark ? 'bg-amber-500/10 border-amber-500/30' : 'bg-amber-50 border-amber-200'}`}>
                  <p className={`text-xs ${isDark ? 'text-amber-300' : 'text-amber-800'}`}>
                    <strong>💡 Tip:</strong> Don't type answers! Active recall (thinking before revealing) is proven to be more effective for memory.
                  </p>
                </div>
              </div>
              
              <Button onClick={() => setShowHowTo(false)} className="w-full mt-4 bg-purple-600 hover:bg-purple-700">
                Got it!
              </Button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Header with All Sets and help button */}
      <div className="flex items-center justify-between">
        <button
          onClick={() => setShowSetsList(true)}
          className={`flex items-center gap-1.5 text-xs font-medium px-2.5 py-1.5 rounded-lg transition-colors ${isDark ? 'text-amber-400 bg-amber-500/20 hover:bg-amber-500/30' : 'text-amber-600 bg-amber-50 hover:bg-amber-100'}`}
        >
          <Copy className="w-3.5 h-3.5" />
          All Sets
        </button>
        <div className="flex items-center gap-2">
          <span className={`text-xs font-medium ${isDark ? 'text-slate-300' : 'text-slate-600'}`}>
            {currentIndex + 1} / {cards.length}
          </span>
          <span className={`text-xs ${isDark ? 'text-slate-600' : 'text-slate-400'}`}>•</span>
          <span className={`text-xs font-medium ${isDark ? 'text-emerald-400' : 'text-emerald-600'}`}>
            {masteredCount} mastered
          </span>
        </div>
        <button
          onClick={() => setShowHowTo(true)}
          className={`flex items-center gap-1 text-xs font-medium ${isDark ? 'text-purple-400 hover:text-purple-300' : 'text-purple-600 hover:text-purple-700'}`}
        >
          <HelpCircle className="w-3.5 h-3.5" />
          How to use
        </button>
      </div>

      {/* Sets List Modal */}
      <AnimatePresence>
        {showSetsList && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"
            onClick={() => setShowSetsList(false)}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className={`rounded-2xl max-w-sm w-full p-5 shadow-2xl max-h-[70vh] overflow-y-auto ${isDark ? 'bg-[#12121a]' : 'bg-white'}`}
              onClick={e => e.stopPropagation()}
            >
              <div className="flex items-center justify-between mb-4">
                <h3 className={`text-lg font-bold ${isDark ? 'text-white' : 'text-slate-900'}`}>Flashcard Sets</h3>
                <button onClick={() => setShowSetsList(false)} className={`p-1 rounded-full ${isDark ? 'hover:bg-white/10' : 'hover:bg-slate-100'}`}>
                  <X className="w-5 h-5 text-slate-500" />
                </button>
              </div>
              
              {/* Group cards by topic */}
              {(() => {
                const setMap = new Map();
                cards.forEach(card => {
                  const topic = card.topics?.[0] || 'General';
                  if (!setMap.has(topic)) {
                    setMap.set(topic, { topic, cards: [], mastered: 0 });
                  }
                  const set = setMap.get(topic);
                  set.cards.push(card);
                  if (card.mastered) set.mastered++;
                });
                const sets = Array.from(setMap.values());
                
                return (
                  <div className="space-y-2">
                    {sets.map((set, idx) => {
                      const progress = (set.mastered / set.cards.length) * 100;
                      return (
                        <button
                          key={set.topic}
                          onClick={() => {
                            // Jump to first card of this topic
                            const firstIdx = cards.findIndex(c => (c.topics?.[0] || 'General') === set.topic);
                            if (firstIdx >= 0) {
                              setCurrentIndex(firstIdx);
                              setIsFlipped(false);
                            }
                            setShowSetsList(false);
                          }}
                          className="w-full p-3 bg-slate-50 hover:bg-purple-50 rounded-xl border border-slate-200 hover:border-purple-300 transition-all text-left"
                        >
                          <div className="flex items-center justify-between mb-2">
                            <span className={`font-semibold text-sm ${isDark ? 'text-slate-100' : 'text-slate-900'}`}>{set.topic}</span>
                            <span className={`text-xs ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>{set.mastered}/{set.cards.length}</span>
                          </div>
                          <div className={`h-1.5 rounded-full overflow-hidden ${isDark ? 'bg-white/10' : 'bg-slate-200'}`}>
                            <div 
                              className="h-full bg-gradient-to-r from-amber-500 to-orange-500 rounded-full"
                              style={{ width: `${progress}%` }}
                            />
                          </div>
                        </button>
                      );
                    })}
                  </div>
                );
              })()}
              
              <Button 
                onClick={handleRegenerate}
                variant="outline"
                className="w-full mt-4"
              >
                <RotateCcw className="w-3.5 h-3.5 mr-2" />
                Generate New Set
              </Button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <Progress value={progress} className="h-1.5" />

      {/* Session stats - always show */}
      <div className="flex justify-center items-center gap-3 text-xs">
        <span className={`px-2 py-1 rounded-lg ${isDark ? 'text-slate-300 bg-white/5' : 'text-slate-500 bg-slate-50'}`}>
          Session: <span className={`font-semibold ${isDark ? 'text-slate-100' : 'text-slate-700'}`}>{sessionStats.correct}/{sessionStats.reviewed}</span> correct
        </span>
        {streakCount >= 2 && (
          <motion.span 
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            className={`px-2 py-1 rounded-lg font-bold flex items-center gap-1 ${isDark ? 'bg-orange-500/20 text-orange-300' : 'bg-orange-100 text-orange-700'}`}
          >
            🔥 {streakCount} streak!
          </motion.span>
        )}
      </div>

      {/* Flashcard */}
      <div 
        onClick={handleFlip}
        className="cursor-pointer select-none"
      >
        <Card className="border-0 shadow-xl overflow-hidden min-h-[280px] relative">
          <AnimatePresence mode="wait">
            {!isFlipped ? (
              <motion.div
                key="question"
                initial={{ rotateY: 90, opacity: 0 }}
                animate={{ rotateY: 0, opacity: 1 }}
                exit={{ rotateY: -90, opacity: 0 }}
                transition={{ duration: 0.2 }}
                className="h-full"
              >
                {/* Question side */}
                <div className="bg-gradient-to-r from-purple-600 to-purple-800 p-3 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Sparkles className="w-4 h-4 text-white" />
                    <span className="font-semibold text-sm text-white">Question</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge className={`text-[10px] ${isDark ? 'bg-purple-500/30 text-purple-200 border-purple-400/30' : getDifficultyColor(currentCard.difficulty)}`}>
                      {currentCard.difficulty}
                    </Badge>
                    {/* Ask AI Button */}
                    <div onClick={(e) => e.stopPropagation()}>
                      <AskAIButton type="flashcard" data={currentCard} lesson={lesson} size="sm" />
                    </div>
                  </div>
                </div>
                <div className={`p-6 flex flex-col items-center justify-center min-h-[220px] ${isDark ? 'bg-[#12121a]' : 'bg-white'}`}>
                  <p className={`text-base font-medium leading-relaxed text-center mb-6 ${isDark ? 'text-slate-100' : 'text-slate-900'}`}>
                    {currentCard.question}
                  </p>
                  <div className="text-center">
                    <p className={`text-xs mb-1 ${isDark ? 'text-slate-500' : 'text-slate-400'}`}>Think of the answer, then...</p>
                    <p className={`text-sm font-semibold ${isDark ? 'text-purple-400' : 'text-purple-600'}`}>Tap to reveal →</p>
                  </div>
                </div>
              </motion.div>
            ) : (
              <motion.div
                key="answer"
                initial={{ rotateY: -90, opacity: 0 }}
                animate={{ rotateY: 0, opacity: 1 }}
                exit={{ rotateY: 90, opacity: 0 }}
                transition={{ duration: 0.2 }}
                className="h-full"
              >
                {/* Answer side */}
                <div className="bg-gradient-to-r from-emerald-500 to-teal-600 p-3 flex items-center justify-between">
                  <span className="font-semibold text-sm text-white">Answer</span>
                  <div className="flex items-center gap-1">
                    <span className="text-[10px] text-white/80">Progress:</span>
                    <div className="flex gap-0.5">
                      {[1,2,3].map(i => (
                        <div 
                          key={i} 
                          className={`w-2 h-2 rounded-full ${i <= (currentCard.review_count || 0) ? 'bg-emerald-500' : 'bg-white/30'}`}
                        />
                      ))}
                    </div>
                    {currentCard.mastered && <span className="text-[10px] ml-1">✓</span>}
                  </div>
                </div>
                <div className={`p-6 flex flex-col min-h-[220px] ${isDark ? 'bg-[#12121a]' : 'bg-white'}`}>
                  <p className={`text-sm leading-relaxed text-center flex-1 flex items-center justify-center ${isDark ? 'text-slate-100' : 'text-slate-900'}`}>
                    {currentCard.answer}
                  </p>
                  
                  {/* Rating section */}
                  <div className={`mt-4 pt-4 border-t ${isDark ? 'border-white/10' : 'border-slate-100'}`}>
                    <p className={`text-xs text-center mb-3 ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>Did you know the answer?</p>
                    <div className="grid grid-cols-2 gap-3">
                      <button
                        onClick={(e) => { e.stopPropagation(); handleRating(false); }}
                        className="bg-gradient-to-br from-red-500 to-red-600 hover:from-red-600 hover:to-red-700 text-white rounded-xl py-3 px-4 shadow-lg transition-all active:scale-95"
                      >
                        <div className="flex items-center justify-center gap-2">
                          <span className="text-lg">❌</span>
                          <div className="text-left">
                            <div className="font-bold text-sm">Nope</div>
                            <div className="text-[10px] opacity-90">Show more often</div>
                          </div>
                        </div>
                      </button>
                      <button
                        onClick={(e) => { e.stopPropagation(); handleRating(true); }}
                        className="bg-gradient-to-br from-emerald-500 to-emerald-600 hover:from-emerald-600 hover:to-emerald-700 text-white rounded-xl py-3 px-4 shadow-lg transition-all active:scale-95"
                      >
                        <div className="flex items-center justify-center gap-2">
                          <span className="text-lg">✅</span>
                          <div className="text-left">
                            <div className="font-bold text-sm">Got it!</div>
                            <div className="text-[10px] opacity-90">Show less often</div>
                          </div>
                        </div>
                      </button>
                    </div>
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </Card>
      </div>

      {/* Navigation & Actions */}
      <div className="flex items-center justify-between">
        <button
          onClick={handlePrev}
          className={`p-2 rounded-full transition-colors ${isDark ? 'hover:bg-white/10' : 'hover:bg-slate-100'}`}
        >
          <ChevronLeft className={`w-5 h-5 ${isDark ? 'text-slate-300' : 'text-slate-600'}`} />
        </button>
        
        <div className="flex gap-2">
          <Button 
            variant="outline" 
            size="sm" 
            onClick={handleShuffle}
            className="text-xs h-8"
          >
            <Shuffle className="w-3 h-3 mr-1" />
            Shuffle
          </Button>
          <Button 
            variant="outline" 
            size="sm" 
            onClick={handleRegenerate}
            className="text-xs h-8"
          >
            <RotateCcw className="w-3 h-3 mr-1" />
            New Cards
          </Button>
        </div>
        
        <button
          onClick={handleNext}
          className={`p-2 rounded-full transition-colors ${isDark ? 'hover:bg-white/10' : 'hover:bg-slate-100'}`}
        >
          <ChevronRight className={`w-5 h-5 ${isDark ? 'text-slate-300' : 'text-slate-600'}`} />
        </button>
      </div>

      {/* XP Toast */}
      <XPGainToast 
        xpGained={xpToast.xp}
        reason={xpToast.reason}
        show={xpToast.show}
        onComplete={() => setXpToast({ show: false, xp: 0, reason: '' })}
      />
    </div>
  );
}