import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Loader2, Settings2, RefreshCw, Copy, Check, Zap, Sparkles, BookOpen, GraduationCap, FileText, Download, Notebook } from "lucide-react";
import ReactMarkdown from "react-markdown";
import NoteSettingsModal from "@/components/modals/NoteSettingsModal";
import { toast } from "sonner";
import EducationalLoader from "@/components/ui/EducationalLoader";

const TYPE_CONFIG = {
  "Detailed Notes": { icon: BookOpen, color: "text-blue-600", bg: "bg-blue-50", border: "border-blue-100" },
  "Cheat Sheet": { icon: Zap, color: "text-amber-600", bg: "bg-amber-50", border: "border-amber-100" },
  "Short Summary": { icon: FileText, color: "text-emerald-600", bg: "bg-emerald-50", border: "border-emerald-100" },
  "Exam Prep": { icon: GraduationCap, color: "text-purple-600", bg: "bg-purple-50", border: "border-purple-100" },
  "default": { icon: Sparkles, color: "text-violet-600", bg: "bg-violet-50", border: "border-violet-100" }
};

export default function NotesTab({ lesson }) {
  const [note, setNote] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [settings, setSettings] = useState({
    noteType: "Detailed Notes",
    customInstructions: ""
  });
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (lesson?.id) {
      loadNotes();
    }
  }, [lesson?.id]);

  const loadNotes = async () => {
    try {
      const notes = await base44.entities.LessonNote.filter({ lesson_id: lesson.id }, '-created_date', 1);
      if (notes && notes.length > 0) {
        setNote(notes[0]);
        setSettings({
          noteType: notes[0].note_type,
          customInstructions: notes[0].custom_instructions || ""
        });
      }
    } catch (error) {
      console.error("Error loading notes:", error);
    }
  };

  const generateNotes = async (currentSettings = settings) => {
    setIsLoading(true);
    try {
      const content = lesson.compressed_content || lesson.extracted_content || lesson.description;
      
      if (!content) {
        toast.error("No lesson content available to generate notes.");
        setIsLoading(false);
        return;
      }

      const { data } = await base44.functions.invoke('generateLessonNotes', {
        lesson_content: content,
        note_type: currentSettings.noteType,
        custom_instructions: currentSettings.customInstructions
      });

      if (data?.content) {
        const newNote = await base44.entities.LessonNote.create({
          lesson_id: lesson.id,
          note_type: currentSettings.noteType,
          content: data.content,
          custom_instructions: currentSettings.customInstructions
        });
        setNote(newNote);
        toast.success(`${currentSettings.noteType} generated!`);
      }
    } catch (error) {
      console.error("Error generating notes:", error);
      toast.error("Failed to generate notes. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleSettingsSave = (newSettings) => {
    setSettings(newSettings);
  };

  const copyToClipboard = () => {
    if (note?.content) {
      navigator.clipboard.writeText(note.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      toast.success("Notes copied to clipboard");
    }
  };

  const activeConfig = TYPE_CONFIG[note?.note_type] || TYPE_CONFIG["default"];
  const ActiveIcon = activeConfig.icon;

  if (isLoading) {
    return (
      <EducationalLoader 
        title="Crafting Your Notes" 
        description={`Our AI is synthesizing a perfect ${settings.noteType.toLowerCase()} for you...`} 
      />
    );
  }

  return (
    <div className="h-full flex flex-col relative bg-slate-50/50">
      <NoteSettingsModal 
        open={settingsOpen} 
        onOpenChange={setSettingsOpen} 
        settings={settings} 
        onSave={handleSettingsSave} 
      />

      {note ? (
        <div className="flex flex-col h-full">
          {/* Header */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between p-4 sm:px-6 bg-white border-b border-slate-200 sticky top-0 z-10 shadow-sm gap-3">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-purple-100 text-purple-600 border border-purple-200">
                <Notebook className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-bold text-slate-900 text-lg leading-none">{note.note_type}</h3>
                <div className="flex items-center gap-2 mt-1">
                  <span className="text-xs text-slate-500 font-medium">Generated by AI Tutor</span>
                  {note.custom_instructions && (
                    <span className="text-[10px] bg-violet-100 text-violet-700 px-2 py-0.5 rounded-full font-bold uppercase tracking-wide">Custom</span>
                  )}
                </div>
              </div>
            </div>
            
            <div className="flex items-center gap-2 sm:self-auto self-end">
              <Button 
                variant="outline" 
                size="sm" 
                onClick={copyToClipboard} 
                className="text-slate-600 border-slate-200 hover:bg-slate-50 hover:text-slate-900"
              >
                {copied ? <Check className="w-4 h-4 mr-1.5 text-emerald-500" /> : <Copy className="w-4 h-4 mr-1.5" />}
                {copied ? "Copied" : "Copy"}
              </Button>
              <Button 
                variant="outline" 
                size="sm" 
                onClick={() => setSettingsOpen(true)} 
                className="text-purple-700 border-purple-200 hover:bg-purple-50 hover:text-purple-900 hover:border-purple-300 transition-all"
              >
                <Settings2 className="w-4 h-4 mr-1.5" />
                Customize
              </Button>
              <Button 
                size="sm" 
                onClick={() => generateNotes(settings)} 
                className="bg-purple-600 hover:bg-purple-700 text-white shadow-md shadow-purple-200 transition-all"
              >
                <RefreshCw className="w-4 h-4 mr-1.5" />
                Regenerate
              </Button>
            </div>
          </div>

          {/* Content */}
          <div className="flex-1 overflow-y-auto p-4 sm:p-8 bg-slate-50/50">
            <div className="max-w-4xl mx-auto">
              <Card className="p-8 sm:p-10 shadow-sm border-slate-200 bg-white">
                <div className="prose prose-slate max-w-none 
                  prose-headings:font-bold prose-headings:text-slate-900 
                  prose-h1:text-3xl prose-h1:border-b prose-h1:border-slate-100 prose-h1:pb-4 prose-h1:mb-6
                  prose-h2:text-2xl prose-h2:text-violet-700 prose-h2:mt-8 prose-h2:mb-4
                  prose-h3:text-xl prose-h3:text-slate-800 prose-h3:mt-6 prose-h3:mb-3
                  prose-p:text-slate-700 prose-p:leading-relaxed prose-p:text-base
                  prose-li:text-slate-700 prose-li:marker:text-violet-400 prose-li:text-base
                  prose-strong:text-slate-900 prose-strong:font-bold
                  prose-em:text-slate-700 prose-em:italic
                  prose-ul:my-4 prose-ol:my-4
                  prose-blockquote:border-l-4 prose-blockquote:border-violet-500 prose-blockquote:bg-violet-50 prose-blockquote:py-2 prose-blockquote:px-4 prose-blockquote:rounded-r-lg prose-blockquote:text-violet-800 prose-blockquote:not-italic
                  prose-code:bg-slate-100 prose-code:text-slate-700 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded-md prose-code:before:content-none prose-code:after:content-none prose-code:font-mono prose-code:text-sm
                  prose-pre:bg-slate-900 prose-pre:text-slate-50 prose-pre:rounded-xl prose-pre:shadow-lg prose-pre:p-4
                  prose-hr:border-slate-200 prose-hr:my-8
                  prose-table:text-sm
                ">
                  <ReactMarkdown>{note.content}</ReactMarkdown>
                </div>
              </Card>
              
              <div className="mt-8 text-center text-slate-400 text-xs">
                Generated content may contain inaccuracies. Always verify with your course materials.
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div className="flex-1 overflow-y-auto p-4 md:p-8 bg-white">
          <div className="max-w-md mx-auto text-center py-8">
            <div className="w-20 h-20 md:w-24 md:h-24 bg-violet-100 rounded-3xl rotate-3 flex items-center justify-center mb-6 mx-auto shadow-xl shadow-violet-100">
              <Sparkles className="w-10 h-10 md:w-12 md:h-12 text-violet-600" />
            </div>
            
            <h2 className="text-2xl md:text-3xl font-bold text-slate-900 mb-2 tracking-tight">Note Generator</h2>
            <p className="text-slate-600 text-sm md:text-base mb-6 leading-relaxed px-2">
              Transform your lesson content into structured study materials in seconds.
            </p>
            
            <div className="grid grid-cols-2 gap-2 mb-6">
              <div className="bg-slate-50 p-3 rounded-xl border border-slate-100 text-left">
                <div className="flex items-center gap-1.5 mb-1 text-violet-700 font-bold text-xs">
                  <BookOpen className="w-3.5 h-3.5" /> Detailed Notes
                </div>
                <p className="text-[10px] text-slate-500">Full topic coverage</p>
              </div>
              <div className="bg-slate-50 p-3 rounded-xl border border-slate-100 text-left">
                <div className="flex items-center gap-1.5 mb-1 text-amber-600 font-bold text-xs">
                  <Zap className="w-3.5 h-3.5" /> Cheat Sheets
                </div>
                <p className="text-[10px] text-slate-500">Quick exam references</p>
              </div>
            </div>
            
            <div className="flex flex-col gap-2 w-full">
              <Button 
                onClick={() => generateNotes(settings)}
                className="w-full h-12 bg-violet-600 hover:bg-violet-700 text-white shadow-lg shadow-violet-200 font-semibold"
              >
                <Sparkles className="w-4 h-4 mr-2" />
                Generate Notes
              </Button>
              <Button 
                variant="outline" 
                onClick={() => setSettingsOpen(true)}
                className="w-full h-10 border-slate-200 hover:bg-slate-50 hover:text-slate-900 text-slate-600"
              >
                <Settings2 className="w-4 h-4 mr-2" />
                Customize Settings
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}