import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Loader2, RefreshCw, Copy, Check, Sparkles, ChevronLeft, ChevronRight as ChevronRightIcon, BookOpen, Zap, FileText, GraduationCap } from "lucide-react";
import CustomizeGenerationModal from "@/components/modals/CustomizeGenerationModal";
import EditableNoteContent from "@/components/document-viewer/EditableNoteContent";
import { toast } from "sonner";
import EducationalLoader from "@/components/ui/EducationalLoader";
import { useTheme } from "@/components/theme/ThemeProvider";
import { useSubscription } from "@/components/subscription/SubscriptionContext";

// Module-level lock: prevents the auto-generate effect from firing more than
// once per lesson, even across re-mounts. Critical for avoiding 429 storms
// AND for stopping multiple generations from accumulating during a session.
const autoGenerationLocks = new Set();
// Tracks active study-task generations per lesson+task_id (or per lesson when null)
// to prevent the same `generateFromStudyTask` event firing twice when the user
// switches tabs quickly.
const studyTaskGenerationLocks = new Set();

const TYPE_CONFIG = {
  "Detailed Notes": { icon: BookOpen, color: "text-blue-600", bg: "bg-blue-50", border: "border-blue-100" },
  "Cheat Sheet": { icon: Zap, color: "text-amber-600", bg: "bg-amber-50", border: "border-amber-100" },
  "Short Summary": { icon: FileText, color: "text-emerald-600", bg: "bg-emerald-50", border: "border-emerald-100" },
  "Exam Prep": { icon: GraduationCap, color: "text-purple-600", bg: "bg-purple-50", border: "border-purple-100" },
  "default": { icon: Sparkles, color: "text-violet-600", bg: "bg-violet-50", border: "border-violet-100" }
};

export default function NotesTab({ lesson }) {
  const { isDark } = useTheme();
  const { canDoTask, incrementTaskCount, triggerUpgradeModal, isPro } = useSubscription();
  const [note, setNote] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [customizeOpen, setCustomizeOpen] = useState(false);
  const [settings, setSettings] = useState({
    noteType: "Detailed Notes",
    customInstructions: "",
    topics: []
  });
  const [copied, setCopied] = useState(false);
  const [tocCollapsed, setTocCollapsed] = useState(false);

  const [initialLoadDone, setInitialLoadDone] = useState(false);
  const [initialLoading, setInitialLoading] = useState(true);
  const [pendingStudyTaskId, setPendingStudyTaskId] = useState(null);

  useEffect(() => {
    if (lesson?.id && !initialLoadDone) {
      loadNotes();
      setInitialLoadDone(true);
    }
  }, [lesson?.id, initialLoadDone]);

  // Listen for the background auto-generation event fired by CreateLesson
  useEffect(() => {
    if (!lesson?.id) return;
    const handler = (e) => {
      if (e.detail?.lesson_id === lesson.id) loadNotes();
    };
    window.addEventListener('notesAutoGenerated', handler);
    return () => window.removeEventListener('notesAutoGenerated', handler);
  }, [lesson?.id]);

  // Self-healing auto-generation — runs ONCE per lesson per browser session.
  const hasUploadedContent = !!(lesson?.file_url || lesson?.file_urls?.length);
  const hasExtractedContent = (lesson?.extracted_content?.length || 0) > 200;
  useEffect(() => {
    if (!initialLoadDone || note || isLoading) return;
    if (!hasUploadedContent || !hasExtractedContent) return;
    if (autoGenerationLocks.has(lesson.id)) return;
    autoGenerationLocks.add(lesson.id);
    generateNotes(settings);
  }, [initialLoadDone, !!note, isLoading, hasUploadedContent, hasExtractedContent, lesson?.id]);

  // Study-task handler — guards against re-firing on every tab switch.
  useEffect(() => {
    const handleStudyTask = async (e) => {
      if (e.detail?.taskType !== 'review_notes' && e.detail?.task?.task_type !== 'review_notes') return;
      const taskId = e.detail?.task?.task_id || null;
      const lockKey = `${lesson?.id}:${taskId || 'no-task'}`;

      // Hard dedupe: if we already generated for this task in this session, don't repeat.
      if (studyTaskGenerationLocks.has(lockKey)) return;
      setPendingStudyTaskId(taskId);

      // If notes already exist for this task_id, just show them.
      if (taskId && lesson?.id) {
        const existing = await base44.entities.LessonNote.filter({ lesson_id: lesson.id, study_plan_task_id: taskId });
        if (existing?.length > 0) {
          const freshNotes = await base44.entities.LessonNote.filter({ lesson_id: lesson.id }, '-created_date', 50);
          setAllNotes(freshNotes);
          const idx = freshNotes.findIndex(n => n.study_plan_task_id === taskId);
          setNote(freshNotes[idx >= 0 ? idx : 0]);
          setCurrentNoteIndex(idx >= 0 ? idx : 0);
          setPendingStudyTaskId(null);
          studyTaskGenerationLocks.add(lockKey);
          return;
        }
      }

      if (!isLoading) {
        studyTaskGenerationLocks.add(lockKey);
        generateNotes(settings);
      }
    };
    window.addEventListener('generateFromStudyTask', handleStudyTask);
    return () => window.removeEventListener('generateFromStudyTask', handleStudyTask);
  }, [lesson?.id, isLoading, settings]);

  const [allNotes, setAllNotes] = useState([]);
  const [currentNoteIndex, setCurrentNoteIndex] = useState(0);

  const loadNotes = async () => {
    setInitialLoading(true);
    try {
      const notes = await base44.entities.LessonNote.filter({ lesson_id: lesson.id }, '-created_date', 50);
      if (notes && notes.length > 0) {
        setAllNotes(notes);
        setNote(notes[0]);
        setCurrentNoteIndex(0);
        setSettings({
          noteType: notes[0].note_type,
          customInstructions: notes[0].custom_instructions || "",
          topics: []
        });
      }
    } catch (error) {
      console.error("Error loading notes:", error);
    } finally {
      setInitialLoading(false);
    }
  };

  const generateNotes = async (currentSettings = settings) => {
    const taskCheck = await canDoTask('review_notes');
    if (!taskCheck.allowed) {
      triggerUpgradeModal('tasks');
      return;
    }

    setIsLoading(true);
    try {
      const content = lesson.compressed_content || lesson.extracted_content || lesson.description;
      if (!content) {
        toast.error("No lesson content available to generate notes.");
        setIsLoading(false);
        return;
      }

      const { data } = await base44.functions.invoke('generateLessonNotes', {
        lesson_content: content,
        note_type: currentSettings.noteType || "Detailed Notes",
        custom_instructions: currentSettings.customInstructions || "",
        topics: currentSettings.topics || [],
        difficulty: currentSettings.difficulty || undefined
      });

      if (data?.content) {
        await incrementTaskCount('review_notes');
        const taskIdForNote = pendingStudyTaskId || null;
        const newNote = await base44.entities.LessonNote.create({
          lesson_id: lesson.id,
          study_plan_task_id: taskIdForNote,
          note_type: currentSettings.noteType || "Detailed Notes",
          content: data.content,
          custom_instructions: currentSettings.customInstructions || ""
        });
        setPendingStudyTaskId(null);
        const freshNotes = await base44.entities.LessonNote.filter({ lesson_id: lesson.id }, '-created_date', 50);
        setAllNotes(freshNotes);
        setNote(newNote);
        setCurrentNoteIndex(0);
        toast.success(`${currentSettings.noteType || "Notes"} generated!`);

        // Mark the specific review_notes task as complete in study plan
        try {
          const studyPlans = await base44.entities.StudyPlan.filter({ lesson_id: lesson.id, status: 'active' });
          if (studyPlans.length > 0) {
            const plan = studyPlans[0];
            let markedOne = false;
            const updatedTasks = plan.tasks?.map(task => {
              if (task.task_type === 'review_notes' && !task.completed && !markedOne) {
                if (taskIdForNote && task.task_id !== taskIdForNote) return task;
                markedOne = true;
                return {
                  ...task,
                  completed_count: (task.completed_count || 0) + 1,
                  completed: true,
                  completed_date: new Date().toISOString()
                };
              }
              return task;
            });

            const allComplete = updatedTasks?.every(t => t.completed);
            await base44.entities.StudyPlan.update(plan.id, {
              tasks: updatedTasks,
              all_tasks_completed: allComplete,
              official_exam_unlocked: allComplete
            });

            window.dispatchEvent(new CustomEvent('studyActivityCompleted'));
            base44.functions.invoke('runPollyEngine', {
              trigger_event: 'review_notes_completed',
              lesson_id: lesson.id
            }).catch(err => console.warn('Polly trigger failed:', err.message));
          }
        } catch (planError) {
          console.error("Error updating study plan for notes:", planError);
        }
      }
    } catch (error) {
      console.error("Error generating notes:", error);
      toast.error("Failed to generate notes. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  // Called when user submits the customize modal
  const handleCustomGenerate = (opts) => {
    const next = {
      noteType: settings.noteType || "Detailed Notes",
      customInstructions: opts.custom_instructions || "",
      topics: opts.topics || [],
      difficulty: opts.difficulty
    };
    setSettings(next);
    generateNotes(next);
  };

  const copyToClipboard = () => {
    if (note?.content) {
      navigator.clipboard.writeText(note.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      toast.success("Notes copied to clipboard");
    }
  };

  const slugify = (text) =>
    text.toLowerCase().replace(/[^\w\s-]/g, '').replace(/\s+/g, '-').replace(/-+/g, '-').trim();

  const extractTableOfContents = (content) => {
    if (!content) return [];
    // Try HTML headings first, fall back to markdown
    const toc = [];
    if (/<h[1-3]/i.test(content)) {
      const re = /<(h[1-3])[^>]*>([\s\S]*?)<\/\1>/gi;
      let m;
      while ((m = re.exec(content)) !== null) {
        const level = parseInt(m[1].substring(1), 10);
        const text = m[2].replace(/<[^>]+>/g, '').trim();
        if (text) toc.push({ level, text, id: `heading-${slugify(text)}` });
      }
      return toc;
    }
    content.split('\n').forEach((line) => {
      const h1 = line.match(/^#\s+(.+)$/);
      const h2 = line.match(/^##\s+(.+)$/);
      const h3 = line.match(/^###\s+(.+)$/);
      if (h1) toc.push({ level: 1, text: h1[1], id: `heading-${slugify(h1[1])}` });
      else if (h2) toc.push({ level: 2, text: h2[1], id: `heading-${slugify(h2[1])}` });
      else if (h3) toc.push({ level: 3, text: h3[1], id: `heading-${slugify(h3[1])}` });
    });
    return toc;
  };

  const tableOfContents = note ? extractTableOfContents(note.content) : [];

  if (isLoading) {
    return (
      <EducationalLoader
        title="Crafting Your Notes"
        description={`Our AI is synthesizing your ${(settings.noteType || 'notes').toLowerCase()} now...`}
      />
    );
  }

  if (initialLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className={`w-6 h-6 animate-spin ${isDark ? 'text-purple-400' : 'text-purple-600'}`} />
      </div>
    );
  }

  return (
    <div className={`flex flex-col relative w-full max-w-full overflow-x-hidden ${isDark ? 'bg-[#0a0a12]' : 'bg-slate-50'}`}>
      <CustomizeGenerationModal
        open={customizeOpen}
        onOpenChange={setCustomizeOpen}
        type="notes"
        lessonId={lesson?.id}
        compressedContent={lesson?.compressed_content || lesson?.extracted_content}
        onGenerate={handleCustomGenerate}
        initialValues={{ custom_instructions: settings.customInstructions, topics: settings.topics }}
      />

      {note ? (
        <div className="flex flex-col w-full max-w-full overflow-x-hidden">
          {/* Content — Quill toolbar (rendered inside EditableNoteContent) acts as the single header */}
          <div className="flex gap-0 overflow-hidden w-full max-w-full">
            {/* Table of Contents - Desktop Only, Collapsible */}
            {tableOfContents.length > 0 && (
              <div className={`hidden lg:flex flex-col border-r transition-all duration-300 relative ${tocCollapsed ? 'w-10' : 'w-64'} ${isDark ? 'bg-[#0a0a12] border-white/10' : 'bg-slate-50 border-slate-200'}`} style={{ maxHeight: 'calc(100vh - 140px)' }}>
                {!tocCollapsed && (
                  <div className="p-2">
                    <h3 className={`text-xs font-bold uppercase tracking-wider px-2 ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>Contents</h3>
                  </div>
                )}
                {!tocCollapsed && (
                  <nav className="space-y-1 px-4 pb-4 overflow-y-auto flex-1">
                    {tableOfContents.map((item, idx) => (
                      <button
                        key={idx}
                        onClick={() => {
                          const el = document.getElementById(item.id);
                          if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
                        }}
                        className={`block w-full text-left text-sm py-1.5 px-2 rounded transition-colors ${
                          item.level === 1 ? 'font-bold' : item.level === 2 ? 'font-semibold pl-3' : 'pl-5'
                        } ${isDark ? 'text-slate-300 hover:bg-purple-500/10 hover:text-purple-300' : 'text-slate-700 hover:bg-purple-50 hover:text-purple-700'}`}
                      >
                        {item.text}
                      </button>
                    ))}
                  </nav>
                )}
                <button
                  onClick={() => setTocCollapsed(!tocCollapsed)}
                  className={`absolute top-1/2 -translate-y-1/2 -right-3.5 z-10 w-7 h-7 rounded-full border-2 shadow-lg flex items-center justify-center transition-all ${
                    isDark
                      ? 'bg-[#1a1a2e] border-purple-500/40 text-purple-400 hover:bg-purple-500/20 hover:border-purple-400'
                      : 'bg-white border-purple-300 text-purple-600 hover:bg-purple-50 hover:border-purple-400'
                  }`}
                  title={tocCollapsed ? 'Expand contents' : 'Collapse contents'}
                >
                  {tocCollapsed ? <ChevronRightIcon className="w-4 h-4" /> : <ChevronLeft className="w-4 h-4" />}
                </button>
              </div>
            )}

            {/* Main Content */}
            <div className={`flex-1 min-w-0 overflow-y-auto overflow-x-hidden p-2 sm:p-6 ${isDark ? 'bg-[#0a0a12]' : 'bg-slate-50'}`} style={{ boxSizing: 'border-box', maxHeight: 'calc(100vh - 140px)' }}>
              <div className="w-full max-w-full md:max-w-4xl mx-auto" style={{ boxSizing: 'border-box' }}>
                <Card className={`p-3 sm:p-12 shadow-sm overflow-hidden break-words ${isDark ? 'border-purple-500/30 bg-[#12121a]' : 'border-slate-200 bg-white'}`} style={{ userSelect: 'text', WebkitUserSelect: 'text', overflowWrap: 'anywhere', wordBreak: 'break-word' }}>
                  <EditableNoteContent
                    key={note.id}
                    content={note.content}
                    onSave={async (newContent) => {
                      await base44.entities.LessonNote.update(note.id, { content: newContent });
                      const nextNote = { ...note, content: newContent };
                      setNote(nextNote);
                      setAllNotes(prev => prev.map(n => n.id === note.id ? nextNote : n));
                    }}
                    isDark={isDark}
                    toolbarActions={
                      <>
                        {allNotes.length > 1 && (
                          <div className={`flex items-center gap-0.5 px-1.5 py-0.5 rounded-md border ${isDark ? 'border-white/10 bg-white/5' : 'border-slate-200 bg-white'}`}>
                            <button
                              onClick={() => {
                                const newIdx = Math.min(currentNoteIndex + 1, allNotes.length - 1);
                                setCurrentNoteIndex(newIdx);
                                setNote(allNotes[newIdx]);
                              }}
                              disabled={currentNoteIndex >= allNotes.length - 1}
                              className={`p-1 rounded disabled:opacity-30 ${isDark ? 'hover:bg-white/10 text-slate-300' : 'hover:bg-slate-100 text-slate-600'}`}
                              title="Older version"
                            >
                              <ChevronLeft className="w-3.5 h-3.5" />
                            </button>
                            <span className={`text-[11px] font-medium tabular-nums ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                              {currentNoteIndex + 1}/{allNotes.length}
                            </span>
                            <button
                              onClick={() => {
                                const newIdx = Math.max(currentNoteIndex - 1, 0);
                                setCurrentNoteIndex(newIdx);
                                setNote(allNotes[newIdx]);
                              }}
                              disabled={currentNoteIndex <= 0}
                              className={`p-1 rounded disabled:opacity-30 ${isDark ? 'hover:bg-white/10 text-slate-300' : 'hover:bg-slate-100 text-slate-600'}`}
                              title="Newer version"
                            >
                              <ChevronRightIcon className="w-3.5 h-3.5" />
                            </button>
                          </div>
                        )}
                        <button
                          onClick={copyToClipboard}
                          title="Copy notes"
                          className={`h-8 w-8 rounded-md border flex items-center justify-center ${isDark ? 'text-slate-300 border-white/10 bg-white/5 hover:bg-white/10' : 'text-slate-600 border-slate-200 bg-white hover:bg-slate-50'}`}
                        >
                          {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                        </button>
                        <button
                          onClick={() => setCustomizeOpen(true)}
                          title="Regenerate with custom options"
                          className="h-8 px-3 rounded-md bg-purple-600 hover:bg-purple-700 text-white shadow-sm shadow-purple-500/30 flex items-center gap-1.5 text-xs font-semibold"
                        >
                          <RefreshCw className="w-3.5 h-3.5" />
                          <span className="hidden sm:inline">Regenerate</span>
                        </button>
                      </>
                    }
                  />
                </Card>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div className={`overflow-y-auto p-4 ${isDark ? 'bg-[#12121a]' : 'bg-white'}`}>
          <div className="max-w-md mx-auto text-center py-8">
            <div className={`w-20 h-20 md:w-24 md:h-24 rounded-3xl rotate-3 flex items-center justify-center mb-6 mx-auto shadow-xl ${isDark ? 'bg-violet-600/20 shadow-violet-900/50' : 'bg-violet-100 shadow-violet-100'}`}>
              <Sparkles className={`w-10 h-10 md:w-12 md:h-12 ${isDark ? 'text-violet-400' : 'text-violet-600'}`} />
            </div>

            <h2 className={`text-2xl md:text-3xl font-bold mb-2 tracking-tight ${isDark ? 'text-slate-100' : 'text-slate-900'}`}>Note Generator</h2>
            <p className={`text-sm md:text-base mb-6 leading-relaxed px-2 ${isDark ? 'text-slate-300' : 'text-slate-600'}`}>
              Transform your lesson content into structured study materials in seconds.
            </p>

            <div className="flex flex-col gap-2 w-full">
              <Button
                onClick={() => generateNotes(settings)}
                className="w-full h-12 bg-violet-600 hover:bg-violet-700 text-white shadow-lg shadow-violet-200 font-semibold"
              >
                <Sparkles className="w-4 h-4 mr-2" />
                Generate Notes
              </Button>
              <Button
                variant="outline"
                onClick={() => setCustomizeOpen(true)}
                className={`w-full h-10 ${isDark ? 'border-white/10 hover:bg-white/5 hover:text-slate-200 text-slate-300' : 'border-slate-200 hover:bg-slate-50 hover:text-slate-900 text-slate-600'}`}
              >
                <Sparkles className="w-4 h-4 mr-2" />
                Customize & Generate
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}