import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Loader2, RefreshCw, Copy, Check, Sparkles, ChevronLeft, ChevronRight as ChevronRightIcon, BookOpen, Zap, FileText, GraduationCap, FileSearch } from "lucide-react";
import CustomizeGenerationModal from "@/components/modals/CustomizeGenerationModal";
import EditableNoteContent from "@/components/document-viewer/EditableNoteContent";
import { toast } from "sonner";
import EducationalLoader from "@/components/ui/EducationalLoader";
import { useTheme } from "@/components/theme/ThemeProvider";
import { useSubscription } from "@/components/subscription/SubscriptionContext";

// Module-level lock: prevents the auto-generate effect from firing more than
// once per lesson, even across re-mounts. Critical for avoiding 429 storms
// AND for stopping multiple generations from accumulating during a session.
const autoGenerationLocks = new Set();
// Tracks active study-task generations per lesson+task_id (or per lesson when null)
// to prevent the same `generateFromStudyTask` event firing twice when the user
// switches tabs quickly.
const studyTaskGenerationLocks = new Set();

const TYPE_CONFIG = {
  "Detailed Notes": { icon: BookOpen, color: "text-blue-600", bg: "bg-blue-50", border: "border-blue-100" },
  "Cheat Sheet": { icon: Zap, color: "text-amber-600", bg: "bg-amber-50", border: "border-amber-100" },
  "Short Summary": { icon: FileText, color: "text-emerald-600", bg: "bg-emerald-50", border: "border-emerald-100" },
  "Exam Prep": { icon: GraduationCap, color: "text-purple-600", bg: "bg-purple-50", border: "border-purple-100" },
  "default": { icon: Sparkles, color: "text-violet-600", bg: "bg-violet-50", border: "border-violet-100" }
};

export default function NotesTab({ lesson, onViewDocument }) {
  const hasDocument = !!(lesson?.file_url || lesson?.file_urls?.length);
  const { isDark } = useTheme();
  const { canDoTask, incrementTaskCount, triggerUpgradeModal, isPro } = useSubscription();
  const [note, setNote] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [customizeOpen, setCustomizeOpen] = useState(false);
  const [settings, setSettings] = useState({
    noteType: "Detailed Notes",
    customInstructions: "",
    topics: []
  });
  const [copied, setCopied] = useState(false);

  // Synchronous in-flight guard. `isLoading` is React state and updates
  // asynchronously, so two rapid clicks can both pass the `if (isLoading)`
  // check before the first re-render — creating duplicate notes. This ref
  // flips synchronously, closing that window at the root.
  const generatingRef = React.useRef(false);

  // `initialLoading` starts true and flips to false only AFTER loadNotes finishes.
  // Auto-generation must wait for this — otherwise it fires while notes are still
  // being fetched, causing duplicate regenerations on lesson re-open.
  const [initialLoading, setInitialLoading] = useState(true);
  const [pendingStudyTaskId, setPendingStudyTaskId] = useState(null);

  useEffect(() => {
    if (lesson?.id) loadNotes();
  }, [lesson?.id]);

  // REAL-TIME: subscribe to LessonNote changes for this lesson. This is the
  // reliable, device-agnostic mechanism that makes a newly-generated note
  // (including the CreateLesson background job) appear the instant it's saved —
  // no page refresh, no tab-switch, no dependency on the parent lesson prop
  // being re-fetched. Fires for creates from ANY source (bg job, this tab, or
  // another open tab on the same account).
  useEffect(() => {
    if (!lesson?.id) return;
    let cancelled = false;
    const unsubscribe = base44.entities.LessonNote.subscribe((event) => {
      if (cancelled) return;
      // Only react to notes belonging to THIS lesson.
      if (event?.data?.lesson_id && event.data.lesson_id !== lesson.id) return;
      // A note was created/updated/deleted for this lesson — reload the list.
      loadNotes();
    });
    return () => {
      cancelled = true;
      try { unsubscribe?.(); } catch {}
    };
  }, [lesson?.id]);

  // Listen for the background auto-generation event fired by CreateLesson.
  // Belt-and-suspenders alongside the realtime subscription: if the event
  // reaches us first (same tab that started the job), refresh immediately.
  useEffect(() => {
    if (!lesson?.id) return;
    const handler = (e) => {
      if (e.detail?.lesson_id === lesson.id) loadNotes();
    };
    window.addEventListener('notesAutoGenerated', handler);
    return () => window.removeEventListener('notesAutoGenerated', handler);
  }, [lesson?.id]);

  // Self-healing auto-generation — runs ONCE per lesson per browser session,
  // and ONLY after the initial load has finished and confirmed no notes exist.
  //
  // CRITICAL: respect `lesson.notes_generation_status`. If CreateLesson kicked
  // off a background generation (status='pending'), we MUST wait for it —
  // racing it would trigger the upgrade modal (user has no quota left) AND
  // cause duplicate notes when both finish. Only auto-generate here if the
  // background job already finished without producing a note (status==='failed'
  // OR status was never set, meaning this is an old/imported lesson).
  const hasUploadedContent = !!(lesson?.file_url || lesson?.file_urls?.length);
  const hasExtractedContent = (lesson?.extracted_content?.length || 0) > 200;
  const bgNotesPending = lesson?.notes_generation_status === 'pending';
  useEffect(() => {
    if (initialLoading || note || isLoading) return;
    if (!hasUploadedContent || !hasExtractedContent) return;
    if (bgNotesPending) return; // CreateLesson is still working — wait for the event
    if (autoGenerationLocks.has(lesson.id)) return;
    autoGenerationLocks.add(lesson.id);
    generateNotes(settings);
  }, [initialLoading, !!note, isLoading, hasUploadedContent, hasExtractedContent, bgNotesPending, lesson?.id]);

  // FALLBACK POLL — only active while we have NO note yet AND the bg job is
  // pending. The realtime subscription above is the primary path; this catches
  // the rare case where the websocket didn't deliver (flaky network / mobile
  // background tab). Driven off "do we actually have a note" rather than the
  // parent prop, so it self-terminates the moment a note lands from any source.
  useEffect(() => {
    if (!lesson?.id || !bgNotesPending || note) return;
    const interval = setInterval(async () => {
      try {
        const [fresh, notes] = await Promise.all([
          base44.entities.Lesson.filter({ id: lesson.id }),
          base44.entities.LessonNote.filter({ lesson_id: lesson.id }, '-created_date', 1),
        ]);
        const status = fresh?.[0]?.notes_generation_status;
        const hasNote = notes?.length > 0;
        if (hasNote || (status && status !== 'pending')) {
          clearInterval(interval);
          await loadNotes();
          // Tell the parent to refresh the lesson prop too so bgNotesPending
          // clears at the parent level.
          window.dispatchEvent(new CustomEvent('reloadLesson'));
        }
      } catch {}
    }, 2500);
    return () => clearInterval(interval);
  }, [lesson?.id, bgNotesPending, note]);

  // Study-task handler — guards against re-firing on every tab switch.
  useEffect(() => {
    const handleStudyTask = async (e) => {
      if (e.detail?.taskType !== 'review_notes' && e.detail?.task?.task_type !== 'review_notes') return;
      const taskId = e.detail?.task?.task_id || null;
      const lockKey = `${lesson?.id}:${taskId || 'no-task'}`;

      // Hard dedupe: if we already generated for this task in this session, don't repeat.
      if (studyTaskGenerationLocks.has(lockKey)) return;
      setPendingStudyTaskId(taskId);

      // If notes already exist for this task_id, just show them.
      if (taskId && lesson?.id) {
        const existing = await base44.entities.LessonNote.filter({ lesson_id: lesson.id, study_plan_task_id: taskId });
        if (existing?.length > 0) {
          const freshNotes = await base44.entities.LessonNote.filter({ lesson_id: lesson.id }, '-created_date', 50);
          setAllNotes(freshNotes);
          const idx = freshNotes.findIndex(n => n.study_plan_task_id === taskId);
          setNote(freshNotes[idx >= 0 ? idx : 0]);
          setCurrentNoteIndex(idx >= 0 ? idx : 0);
          setPendingStudyTaskId(null);
          studyTaskGenerationLocks.add(lockKey);
          return;
        }
      }

      if (!isLoading) {
        studyTaskGenerationLocks.add(lockKey);
        generateNotes(settings);
      }
    };
    window.addEventListener('generateFromStudyTask', handleStudyTask);
    return () => window.removeEventListener('generateFromStudyTask', handleStudyTask);
  }, [lesson?.id, isLoading, settings]);

  const [allNotes, setAllNotes] = useState([]);
  const [currentNoteIndex, setCurrentNoteIndex] = useState(0);

  // Only show the initial spinner on the FIRST load for this lesson — subsequent
  // reloads (from auto-gen event, polling, or tab re-mount) should refresh in
  // the background without flashing the spinner over already-rendered notes.
  const hasLoadedOnceRef = React.useRef(false);
  const loadNotes = async () => {
    if (!hasLoadedOnceRef.current) setInitialLoading(true);
    try {
      const notes = await base44.entities.LessonNote.filter({ lesson_id: lesson.id }, '-created_date', 50);
      if (notes && notes.length > 0) {
        setAllNotes(notes);
        // Preserve the note the user is currently viewing if it still exists
        // (e.g. a realtime reload shouldn't yank them back to the newest note).
        setNote((prev) => {
          if (!prev) return notes[0];
          const stillThere = notes.find((n) => n.id === prev.id);
          return stillThere || notes[0];
        });
        setCurrentNoteIndex((prevIdx) => {
          // keep index valid
          return prevIdx < notes.length ? prevIdx : 0;
        });
        setSettings((prev) => ({
          noteType: notes[0].note_type,
          customInstructions: notes[0].custom_instructions || "",
          topics: prev?.topics || []
        }));
      } else {
        // No notes exist — make sure we don't keep a stale note around.
        setAllNotes([]);
        setNote(null);
      }
    } catch (error) {
      console.error("Error loading notes:", error);
    } finally {
      hasLoadedOnceRef.current = true;
      setInitialLoading(false);
    }
  };

  const generateNotes = async (currentSettings = settings) => {
    // Root-cause duplicate guard: bail synchronously if a generation is already
    // running, before any await yields control back to the event loop.
    if (generatingRef.current) return;

    const taskCheck = await canDoTask('review_notes');
    if (!taskCheck.allowed) {
      triggerUpgradeModal('notes');
      return;
    }

    generatingRef.current = true;
    setIsLoading(true);
    // Mark the lesson as generating so a mid-flight close leaves a recoverable
    // 'pending' state (NotesTab waits for it on re-open instead of showing an
    // empty CTA). Fire-and-forget — never block note generation on this write.
    base44.entities.Lesson.update(lesson.id, { notes_generation_status: 'pending' }).catch(() => {});
    try {
      const content = lesson.compressed_content || lesson.extracted_content || lesson.description;
      if (!content) {
        toast.error("No lesson content available to generate notes.");
        setIsLoading(false);
        generatingRef.current = false;
        base44.entities.Lesson.update(lesson.id, { notes_generation_status: 'failed' }).catch(() => {});
        return;
      }

      const { data } = await base44.functions.invoke('generateLessonNotes', {
        lesson_content: content,
        note_type: currentSettings.noteType || "Detailed Notes",
        custom_instructions: currentSettings.customInstructions || "",
        topics: currentSettings.topics || [],
        difficulty: currentSettings.difficulty || undefined
      });

      if (data?.content) {
        await incrementTaskCount('review_notes');
        const taskIdForNote = pendingStudyTaskId || null;
        const newNote = await base44.entities.LessonNote.create({
          lesson_id: lesson.id,
          study_plan_task_id: taskIdForNote,
          note_type: currentSettings.noteType || "Detailed Notes",
          content: data.content,
          custom_instructions: currentSettings.customInstructions || ""
        });
        setPendingStudyTaskId(null);
        const freshNotes = await base44.entities.LessonNote.filter({ lesson_id: lesson.id }, '-created_date', 50);
        setAllNotes(freshNotes);
        setNote(newNote);
        setCurrentNoteIndex(0);
        base44.entities.Lesson.update(lesson.id, { notes_generation_status: 'complete' }).catch(() => {});
        toast.success(`${currentSettings.noteType || "Notes"} generated!`);

        // Mark the specific review_notes task as complete in study plan
        try {
          const studyPlans = await base44.entities.StudyPlan.filter({ lesson_id: lesson.id, status: 'active' });
          if (studyPlans.length > 0) {
            const plan = studyPlans[0];
            let markedOne = false;
            const updatedTasks = plan.tasks?.map(task => {
              if (task.task_type === 'review_notes' && !task.completed && !markedOne) {
                if (taskIdForNote && task.task_id !== taskIdForNote) return task;
                markedOne = true;
                return {
                  ...task,
                  completed_count: (task.completed_count || 0) + 1,
                  completed: true,
                  completed_date: new Date().toISOString()
                };
              }
              return task;
            });

            const allComplete = updatedTasks?.every(t => t.completed);
            await base44.entities.StudyPlan.update(plan.id, {
              tasks: updatedTasks,
              all_tasks_completed: allComplete,
              official_exam_unlocked: allComplete
            });

            window.dispatchEvent(new CustomEvent('studyActivityCompleted'));
            base44.functions.invoke('runPollyEngine', {
              trigger_event: 'review_notes_completed',
              lesson_id: lesson.id
            }).catch(err => console.warn('Polly trigger failed:', err.message));
          }
        } catch (planError) {
          console.error("Error updating study plan for notes:", planError);
        }
      }
    } catch (error) {
      console.error("Error generating notes:", error);
      base44.entities.Lesson.update(lesson.id, { notes_generation_status: 'failed' }).catch(() => {});
      toast.error("Failed to generate notes. Please try again.");
    } finally {
      generatingRef.current = false;
      setIsLoading(false);
    }
  };

  // Called when user submits the customize modal
  const handleCustomGenerate = (opts) => {
    const next = {
      noteType: settings.noteType || "Detailed Notes",
      customInstructions: opts.custom_instructions || "",
      topics: opts.topics || [],
      difficulty: opts.difficulty
    };
    setSettings(next);
    generateNotes(next);
  };

  const copyToClipboard = () => {
    if (note?.content) {
      navigator.clipboard.writeText(note.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      toast.success("Notes copied to clipboard");
    }
  };

  if (isLoading) {
    return (
      <EducationalLoader
        title="Crafting Your Notes"
        description={`Our AI is synthesizing your ${(settings.noteType || 'notes').toLowerCase()} now...`}
      />
    );
  }

  // Background auto-generation from CreateLesson is in flight — show the
  // friendly loader instead of the empty state. Covers: (a) bg job still
  // pending, (b) first load hasn't finished, (c) the brief window where a bg
  // job was triggered (uploaded doc + extractable content) but the note hasn't
  // been saved yet — in all these cases a note is imminently arriving via the
  // realtime subscription, so we must NOT flash the "Generate Notes" empty CTA.
  const awaitingBackgroundNote = !note && (bgNotesPending || !hasLoadedOnceRef.current);
  if (awaitingBackgroundNote) {
    return (
      <EducationalLoader
        title="Crafting Your Notes"
        description="Reading your document and writing your first set of notes..."
      />
    );
  }

  if (initialLoading && !note) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className={`w-6 h-6 animate-spin ${isDark ? 'text-purple-400' : 'text-purple-600'}`} />
      </div>
    );
  }

  return (
    <div className={`flex flex-col relative w-full max-w-full overflow-x-hidden ${isDark ? 'bg-[#0a0a12]' : 'bg-white'}`}>
      <CustomizeGenerationModal
        open={customizeOpen}
        onOpenChange={setCustomizeOpen}
        type="notes"
        lessonId={lesson?.id}
        compressedContent={lesson?.compressed_content || lesson?.extracted_content}
        onGenerate={handleCustomGenerate}
        initialValues={{ custom_instructions: settings.customInstructions, topics: settings.topics }}
      />

      {note ? (
        <div className={`flex-1 min-w-0 w-full max-w-full overflow-x-hidden ${isDark ? 'bg-[#12121a]' : 'bg-white'}`}>
          <div className={`px-1 sm:px-8 py-2 w-full max-w-full ${isDark ? 'bg-[#12121a]' : 'bg-white'} min-h-full`} style={{ userSelect: 'text', WebkitUserSelect: 'text', overflowWrap: 'anywhere', wordBreak: 'break-word' }}>
            <EditableNoteContent
              key={note.id}
              content={note.content}
              onSave={async (newContent) => {
                await base44.entities.LessonNote.update(note.id, { content: newContent });
                const nextNote = { ...note, content: newContent };
                setNote(nextNote);
                setAllNotes(prev => prev.map(n => n.id === note.id ? nextNote : n));
              }}
              isDark={isDark}
              toolbarActions={
                <>
                  {hasDocument && onViewDocument && (
                    <button
                      onClick={onViewDocument}
                      title="View source document"
                      className={`h-7 px-2 rounded-md border flex items-center gap-1 text-[11px] font-semibold ${isDark ? 'text-slate-300 border-white/10 bg-white/5 hover:bg-white/10' : 'text-slate-700 border-slate-200 bg-white hover:bg-slate-50'}`}
                    >
                      <FileSearch className="w-3.5 h-3.5" />
                      <span className="hidden sm:inline">Document</span>
                    </button>
                  )}
                  {allNotes.length > 1 && (
                    <div className={`flex items-center gap-0.5 px-1.5 py-0.5 rounded-md border ${isDark ? 'border-white/10 bg-white/5' : 'border-slate-200 bg-white'}`}>
                      <button
                        onClick={() => {
                          const newIdx = Math.min(currentNoteIndex + 1, allNotes.length - 1);
                          setCurrentNoteIndex(newIdx);
                          setNote(allNotes[newIdx]);
                        }}
                        disabled={currentNoteIndex >= allNotes.length - 1}
                        className={`p-1 rounded disabled:opacity-30 ${isDark ? 'hover:bg-white/10 text-slate-300' : 'hover:bg-slate-100 text-slate-600'}`}
                        title="Older version"
                      >
                        <ChevronLeft className="w-3.5 h-3.5" />
                      </button>
                      <span className={`text-[11px] font-medium tabular-nums ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                        {currentNoteIndex + 1}/{allNotes.length}
                      </span>
                      <button
                        onClick={() => {
                          const newIdx = Math.max(currentNoteIndex - 1, 0);
                          setCurrentNoteIndex(newIdx);
                          setNote(allNotes[newIdx]);
                        }}
                        disabled={currentNoteIndex <= 0}
                        className={`p-1 rounded disabled:opacity-30 ${isDark ? 'hover:bg-white/10 text-slate-300' : 'hover:bg-slate-100 text-slate-600'}`}
                        title="Newer version"
                      >
                        <ChevronRightIcon className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  )}
                  <button
                    onClick={copyToClipboard}
                    title="Copy notes"
                    className={`h-7 w-7 rounded-md border flex items-center justify-center ${isDark ? 'text-slate-300 border-white/10 bg-white/5 hover:bg-white/10' : 'text-slate-600 border-slate-200 bg-white hover:bg-slate-50'}`}
                  >
                    {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                  </button>
                  <button
                    onClick={() => setCustomizeOpen(true)}
                    title="Regenerate with custom options"
                    className="h-7 px-2.5 rounded-md bg-purple-600 hover:bg-purple-700 text-white shadow-sm shadow-purple-500/30 flex items-center gap-1 text-[11px] font-semibold"
                  >
                    <RefreshCw className="w-3.5 h-3.5" />
                    <span className="hidden sm:inline">Regenerate</span>
                  </button>
                </>
              }
            />
          </div>
        </div>
      ) : (
        <div className={`overflow-y-auto p-4 ${isDark ? 'bg-[#12121a]' : 'bg-white'}`}>
          <div className="max-w-md mx-auto text-center py-8">
            <div className={`w-20 h-20 md:w-24 md:h-24 rounded-3xl rotate-3 flex items-center justify-center mb-6 mx-auto shadow-xl ${isDark ? 'bg-violet-600/20 shadow-violet-900/50' : 'bg-violet-100 shadow-violet-100'}`}>
              <Sparkles className={`w-10 h-10 md:w-12 md:h-12 ${isDark ? 'text-violet-400' : 'text-violet-600'}`} />
            </div>

            <h2 className={`text-2xl md:text-3xl font-bold mb-2 tracking-tight ${isDark ? 'text-slate-100' : 'text-slate-900'}`}>Note Generator</h2>
            {lesson?.notes_generation_status === 'failed' ? (
              <p className={`text-sm md:text-base mb-6 leading-relaxed px-2 font-medium ${isDark ? 'text-amber-400' : 'text-amber-600'}`}>
                We couldn't generate your notes last time. Tap below to try again.
              </p>
            ) : (
              <p className={`text-sm md:text-base mb-6 leading-relaxed px-2 ${isDark ? 'text-slate-300' : 'text-slate-600'}`}>
                Transform your lesson content into structured study materials in seconds.
              </p>
            )}

            <div className="flex flex-col gap-2 w-full">
              <Button
                onClick={() => generateNotes(settings)}
                className="w-full h-12 bg-violet-600 hover:bg-violet-700 text-white shadow-lg shadow-violet-200 font-semibold"
              >
                <Sparkles className="w-4 h-4 mr-2" />
                Generate Notes
              </Button>
              <Button
                variant="outline"
                onClick={() => setCustomizeOpen(true)}
                className={`w-full h-10 ${isDark ? 'border-white/10 hover:bg-white/5 hover:text-slate-200 text-slate-300' : 'border-slate-200 hover:bg-slate-50 hover:text-slate-900 text-slate-600'}`}
              >
                <Sparkles className="w-4 h-4 mr-2" />
                Customize & Generate
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}