import React, { useState, useEffect, useRef } from "react";
import { base44 } from "@/api/base44Client";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { motion, AnimatePresence } from "framer-motion";
import { Loader2, Lightbulb, CheckCircle2, AlertCircle, Sparkles, RefreshCw, PenLine, HelpCircle, Brain, X } from "lucide-react";
import AskAIButton from "@/components/ai-tutor/AskAIButton";
import EducationalLoader from "@/components/ui/EducationalLoader";
import { awardDailyXP } from "@/components/utils/dailyReset";
import XPGainToast from "@/components/gamification/XPGainToast";
import TeachItSetsList from "./TeachItSetsList";
import { useSubscription } from "@/components/subscription/SubscriptionContext";
import { useTheme } from "@/components/theme/ThemeProvider";
import MathText from "@/components/math/MathText";
import CustomizeGenerationModal from "@/components/modals/CustomizeGenerationModal";
import LockedTeachItInput from "@/components/teach-it/LockedTeachItInput";

export default function TeachItTab({ lesson, focusTopics, extractedContent }) {
  const { canDoTask, incrementTaskCount, triggerUpgradeModal, isPro } = useSubscription();
  const { isDark } = useTheme();
  const [cards, setCards] = useState([]);
  const [currentCardIndex, setCurrentCardIndex] = useState(0);
  const [userAnswer, setUserAnswer] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [isGrading, setIsGrading] = useState(false);
  const [showFeedback, setShowFeedback] = useState(false);
  const [xpToast, setXpToast] = useState({ show: false, xp: 0, reason: '' });
  const [studyPlanTopics, setStudyPlanTopics] = useState(null);
  const [showSetsList, setShowSetsList] = useState(true);
  const [showCustomize, setShowCustomize] = useState(false);
  const [currentSetCardIds, setCurrentSetCardIds] = useState(null); // IDs of cards in the active set
  const tabContainerRef = useRef(null);

  const isGeneratingRef = useRef(false);
  const hasAutoGeneratedRef = useRef(false);

  useEffect(() => {
    if (lesson?.id) {
      loadCards();
    }
  }, [lesson?.id]);

  const studyTaskHandledRef = useRef(false);
  
  const pendingStudyTaskRef = useRef(null);
  
  useEffect(() => {
    // navigateToStudyTask: check for existing set by study_plan_task_id, only generate if none found
    const handleNavigateToTask = async (e) => {
      if (e.detail.taskType !== 'teach_it') return;
      if (studyTaskHandledRef.current || isGeneratingRef.current) return;
      studyTaskHandledRef.current = true;
      
      const task = e.detail.task;
      const taskId = task?.task_id;
      
      // Check by study_plan_task_id in DB (reliable, works even if cards not loaded yet)
      if (taskId && lesson?.id) {
        const existing = await base44.entities.TeachItCard.filter({ lesson_id: lesson.id, study_plan_task_id: taskId });
        if (existing?.length > 0) {
          // Reload all cards and navigate to the existing set
          const allCards = await base44.entities.TeachItCard.filter({ lesson_id: lesson.id });
          setCards(allCards);
          const setCardIds = existing.map(c => c.id);
          const firstIdx = allCards.findIndex(c => c.id === existing[0].id);
          if (firstIdx >= 0) {
            setCurrentCardIndex(firstIdx);
            setUserAnswer(allCards[firstIdx].user_answer || "");
            setShowFeedback(allCards[firstIdx].completed);
            setCurrentSetCardIds(setCardIds);
            setShowSetsList(false);
          }
          setTimeout(() => { studyTaskHandledRef.current = false; }, 2000);
          return;
        }
      }
      
      // No existing set — generate new
      pendingStudyTaskRef.current = task;
      generateCards();
      setTimeout(() => { studyTaskHandledRef.current = false; }, 2000);
    };
    
    // generateFromStudyTask: always generate (used by "Pick Format" modal etc.)
    const handleGenerateTask = async (e) => {
      if (e.detail.taskType !== 'teach_it') return;
      if (studyTaskHandledRef.current || isGeneratingRef.current) return;
      studyTaskHandledRef.current = true;
      pendingStudyTaskRef.current = e.detail.task;
      generateCards();
      setTimeout(() => { studyTaskHandledRef.current = false; }, 2000);
    };
    
    window.addEventListener('navigateToStudyTask', handleNavigateToTask);
    window.addEventListener('generateFromStudyTask', handleGenerateTask);
    return () => {
      window.removeEventListener('navigateToStudyTask', handleNavigateToTask);
      window.removeEventListener('generateFromStudyTask', handleGenerateTask);
    };
  }, [lesson?.id]);
  
  const loadStudyPlanTopics = async () => {
    if (!lesson?.id) return;
    try {
      const plans = await base44.entities.StudyPlan.filter({ lesson_id: lesson.id, status: 'active' });
      if (plans.length > 0) {
        const teachItTask = plans[0].tasks?.find(t => t.task_type === 'teach_it' && !t.completed);
        if (teachItTask?.focus_topics?.length > 0) {
          setStudyPlanTopics(teachItTask.focus_topics);
        }
      }
    } catch (error) {
      console.error("Error loading study plan topics:", error);
    }
  };

  const loadCards = async () => {
    try {
      const existingCards = await base44.entities.TeachItCard.filter({ lesson_id: lesson.id });
      if (existingCards?.length > 0) {
        setCards(existingCards);
        setShowSetsList(true);
        const incompleteIndex = existingCards.findIndex(c => !c.completed);
        setCurrentCardIndex(incompleteIndex >= 0 ? incompleteIndex : 0);
      }
    } catch (error) {
      console.error("Error loading cards:", error);
    }
  };

  const generateCards = async (customOptions = null) => {
    if (isGeneratingRef.current) return;
    const taskCheck = await canDoTask('teach_it');
    if (!taskCheck.allowed) { triggerUpgradeModal('tasks'); return; }
    
    isGeneratingRef.current = true;
    setIsGenerating(true);
    
    try {
      const user = await base44.auth.me();
      const profile = await base44.entities.LearningProfile.filter({ id: user.learning_profile_id });
      const learningProfile = profile[0] || {};

      let contentDescription = "";
      if (lesson.input_type === "description" && lesson.description) {
        contentDescription = lesson.description;
      } else if (lesson.compressed_content) {
        contentDescription = lesson.compressed_content;
      } else if (lesson.extracted_content) {
        contentDescription = lesson.extracted_content.length > 50000 
          ? lesson.extracted_content.substring(0, 50000) + "\n...[content truncated]"
          : lesson.extracted_content;
      } else {
        contentDescription = lesson.description || "N/A";
      }

      const studyTaskTopics = pendingStudyTaskRef.current?.focus_topics;
      const topicsToFocus = customOptions?.topics?.length > 0 ? customOptions.topics : (studyTaskTopics || focusTopics || studyPlanTopics);
      const cardCount = customOptions?.amount || 5;
      const difficultyPref = customOptions?.difficulty || 'mixed';
      const customInstructions = customOptions?.custom_instructions || '';

      const focusInstruction = topicsToFocus?.length > 0 
        ? `\n\nPRIORITY FOCUS TOPICS (from student's study plan - they struggled with these):
${topicsToFocus.map((t, i) => `${i + 1}. ${t}`).join('\n')}
Generate cards that specifically address these topics. At least ${Math.ceil(cardCount * 0.6)} of the ${cardCount} cards MUST directly cover these focus areas.`
        : '';

      const difficultyInstruction = difficultyPref !== 'mixed'
        ? `\n\nDIFFICULTY: All cards should be at "${difficultyPref}" difficulty level.`
        : `\n\nDIFFICULTY: Mix easy, medium, and hard cards for a balanced set.`;

      const customInstructionBlock = customInstructions 
        ? `\n\nCUSTOM STUDENT INSTRUCTIONS (follow these closely):\n${customInstructions}`
        : '';

      const prompt = `You are an expert educator creating "Teach It" cards for ${lesson.course_name}.

CONTEXT:
Student Grade: ${learningProfile.grade || "N/A"}
Course: ${lesson.course_name}
School: ${learningProfile.school || "N/A"}

STUDENT'S MATERIAL:
${contentDescription}
${focusInstruction}
${difficultyInstruction}
${customInstructionBlock}

CRITICAL INSTRUCTIONS:
1. Read the student's material carefully and identify ${cardCount} SPECIFIC, CONCRETE concepts that are EXPLICITLY covered in their content
2. DO NOT ask meta-questions like "Why do we study X?" or "What problem does X solve?"
3. DO NOT ask about the purpose or value of studying the topic
4. ONLY ask about SPECIFIC content from their material: theories, processes, mechanisms, relationships, definitions, or applications

WHAT TO EXTRACT:
- Specific theories, laws, or principles mentioned
- Key processes or mechanisms explained
- Important definitions or terminology
- Relationships between specific concepts
- How something works or functions
- Specific examples or case studies discussed

QUESTION FORMATS (use these):
- "Explain how [specific process/mechanism from material] works."
- "What is [specific concept from material] and how does it function?"
- "Describe the relationship between [specific concept A] and [specific concept B] from the material."
- "How does [specific theory/principle] explain [specific phenomenon]?"
- "Walk through the steps of [specific process mentioned in material]."

RULES:
- Extract questions from ACTUAL content in the material
- Questions must be answerable using information FROM their material
- Each card tests a DIFFERENT specific concept
- Model answers: 3-5 sentences, clear explanation using material content
- If content mentions specific examples, theories, or processes - use those

OUTPUT:
Return exactly ${cardCount} cards with question and model_answer fields, each based on specific content from the student's material.`;

      const { data: result } = await base44.functions.invoke('generateTeachItCards', { prompt });
      const generatedCards = result?.cards || [];
      if (generatedCards.length === 0) throw new Error("No cards generated");

      // Determine set label from study task section + topic or custom options
      const taskRef = pendingStudyTaskRef.current;
      const taskIdForCards = taskRef?.task_id || null;
      const setLabel = taskRef?.title || customOptions?.title || null;
      
      const savedCards = await Promise.all(
        generatedCards.map(card =>
          base44.entities.TeachItCard.create({
            lesson_id: lesson.id,
            study_plan_task_id: taskIdForCards,
            question: card.question,
            model_answer: card.model_answer,
            topic: setLabel || card.topic || 'General Concepts',
            completed: false
          })
        )
      );
      pendingStudyTaskRef.current = null;
      await incrementTaskCount('teach_it');

      // Reload all cards so sets list shows all sets including the new one
      const allCards = await base44.entities.TeachItCard.filter({ lesson_id: lesson.id });
      setCards(allCards);
      const newFirstIndex = allCards.findIndex(c => c.id === savedCards[0]?.id);
      setCurrentCardIndex(newFirstIndex >= 0 ? newFirstIndex : 0);
      setCurrentSetCardIds(savedCards.map(c => c.id));
      setShowSetsList(false);
    } catch (error) {
      console.error("Error generating cards:", error);
      alert("Failed to generate cards. Please try again.");
    } finally {
      setIsGenerating(false);
      isGeneratingRef.current = false;
    }
  };

  const gradeAnswer = async () => {
    if (!userAnswer.trim()) return;
    setIsGrading(true);
    try {
      
      const currentCard = cards[currentCardIndex];
      const prompt = `You are grading a student's explanation of a concept.

QUESTION:
${currentCard.question}

MODEL ANSWER:
${currentCard.model_answer}

STUDENT'S ANSWER:
${userAnswer}

GRADING CRITERIA:
1. Conceptual Understanding (40%): Does the student grasp the core concept?
2. Explanation Quality (30%): Is it clear and well-articulated?
3. Completeness (30%): Did they cover the key points?

SCORING:
- 90-100: Excellent - Deep understanding, clear explanation, all key points covered
- 75-89: Good - Solid understanding, mostly clear, covered most points
- 60-74: Fair - Basic understanding, some gaps or unclear explanations
- Below 60: Needs improvement - Missing key concepts or significant misunderstandings

OUTPUT:
Return a score (0-100), feedback (2-3 sentences), strengths array (what they did well), and gaps array (what they missed or misunderstood).`;

      const gradingResult = await base44.integrations.Core.InvokeLLM({
        prompt,
        response_json_schema: {
          type: "object",
          properties: {
            score: { type: "number" },
            feedback: { type: "string" },
            strengths: { type: "array", items: { type: "string" } },
            gaps: { type: "array", items: { type: "string" } }
          }
        }
      });

      const isMastered = gradingResult.score >= 70;
      const updatedCard = await base44.entities.TeachItCard.update(currentCard.id, {
        user_answer: userAnswer,
        score: gradingResult.score,
        feedback: gradingResult.feedback,
        strengths: gradingResult.strengths,
        gaps: gradingResult.gaps,
        completed: true,
        mastered: isMastered
      });

      const fullUpdatedCard = { ...currentCard, ...updatedCard, mastered: isMastered };
      const updatedCards = [...cards];
      updatedCards[currentCardIndex] = fullUpdatedCard;
      setCards(updatedCards);
      setShowFeedback(true);

      const totalCompleted = updatedCards.filter(c => c.completed).length;
      const taskJustCompleted = await updateStudyPlanProgress(totalCompleted);

      // Trigger confetti + Polly after teach-it task completion
      if (taskJustCompleted) {
        window.dispatchEvent(new Event('studyTaskCompleted'));
        base44.functions.invoke('runPollyEngine', {
          trigger_event: 'teach_it_task_completed',
          lesson_id: lesson.id
        }).catch(err => console.warn('Polly trigger failed:', err.message));
      }

      const xpAmount = gradingResult.score >= 90 ? 20 : gradingResult.score >= 75 ? 15 : 10;
      await awardDailyXP(xpAmount, "Taught a concept!");
      setXpToast({ show: true, xp: xpAmount, reason: "Taught a concept!" });

      // Trigger grade micro-movement in header
      window.dispatchEvent(new CustomEvent('studyActivityCompleted'));
    } catch (error) {
      console.error("Error grading answer:", error);
      alert("Failed to grade answer. Please try again.");
    } finally {
      setIsGrading(false);
    }
  };

  const handleNext = () => {
    const nextPosInSet = posInSet + 1;
    if (nextPosInSet < setSize) {
      const nextIdx = setIndices[nextPosInSet];
      setCurrentCardIndex(nextIdx);
      setUserAnswer(cards[nextIdx].user_answer || "");
      setShowFeedback(cards[nextIdx].completed);
    }
  };

  const handlePrevious = () => {
    const prevPosInSet = posInSet - 1;
    if (prevPosInSet >= 0) {
      const prevIdx = setIndices[prevPosInSet];
      setCurrentCardIndex(prevIdx);
      setUserAnswer(cards[prevIdx].user_answer || "");
      setShowFeedback(cards[prevIdx].completed);
    }
  };

  const handleRegenerate = () => {
    // Open the customize modal so user picks topics/difficulty/amount before generating.
    setCurrentCardIndex(0);
    setUserAnswer("");
    setShowFeedback(false);
    setShowCustomize(true);
  };

  const checkIfTaskCompleted = async (taskType, completedCount) => {
    try {
      const plans = await base44.entities.StudyPlan.filter({ lesson_id: lesson.id, status: 'active' });
      if (plans.length === 0) return false;
      const task = plans[0].tasks?.find(t => t.task_type === taskType);
      if (!task || task.completed) return false;
      return completedCount >= (task.target_count || 3);
    } catch { return false; }
  };

  const updateStudyPlanProgress = async (completedCount) => {
    try {
      const plans = await base44.entities.StudyPlan.filter({ lesson_id: lesson.id, status: 'active' });
      if (plans.length === 0) return false;
      const plan = plans[0];
      let taskJustCompleted = false;
      
      const updatedTasks = plan.tasks.map(task => {
        if (task.task_type === 'teach_it') {
          const newCount = completedCount;
          const wasComplete = task.completed;
          const targetCount = task.target_count || 3;
          const isComplete = newCount >= targetCount;
          if (isComplete && !wasComplete) taskJustCompleted = true;
          return {
            ...task,
            completed_count: newCount,
            completed: isComplete,
            completed_date: isComplete && !task.completed_date ? new Date().toISOString() : task.completed_date
          };
        }
        return task;
      });
      
      const allComplete = updatedTasks.every(t => t.completed);
      await base44.entities.StudyPlan.update(plan.id, {
        tasks: updatedTasks,
        all_tasks_completed: allComplete,
        official_exam_unlocked: allComplete
      });
      return taskJustCompleted;
    } catch (error) {
      console.error("Error updating study plan:", error);
      return false;
    }
  };

  if (isGenerating) {
    return (
      <EducationalLoader
        title="Creating Feynman Cards"
        description="Generating foundational concept questions based on your material..."
      />
    );
  }

  if (cards.length > 0 && showSetsList) {
    return (
      <>
        <TeachItSetsList 
          cards={cards}
          onSelectCard={(idx, setCardIds) => {
            setCurrentCardIndex(idx);
            setUserAnswer(cards[idx].user_answer || "");
            setShowFeedback(cards[idx].completed);
            setCurrentSetCardIds(setCardIds || null);
            setShowSetsList(false);
          }}
          onGenerateNew={handleRegenerate}
        />
        <CustomizeGenerationModal
          open={showCustomize}
          onOpenChange={setShowCustomize}
          type="teach_it"
          lessonId={lesson?.id}
          compressedContent={lesson?.compressed_content || extractedContent}
          onGenerate={(opts) => generateCards(opts)}
        />
      </>
    );
  }

  if (cards.length === 0) {
    return (
      <div className={`flex items-center justify-center p-4 pb-8 min-h-[400px] w-full max-w-full ${isDark ? 'bg-[#0a0a12]' : 'bg-slate-50'}`} style={{ boxSizing: 'border-box', overflowX: 'hidden' }}>
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.4 }}
          className="w-full max-w-md md:max-w-xl"
        >
          <Card className={`backdrop-blur-xl border-2 shadow-2xl overflow-hidden ${isDark ? 'bg-[#12121a]/95 border-purple-500/30' : 'bg-white/95 border-purple-200'}`}>
            <div className="bg-gradient-to-r from-purple-600 via-purple-700 to-purple-800 px-6 py-6 md:py-8 text-center">
              <motion.div
                animate={{ rotate: [0, -10, 10, -10, 0] }}
                transition={{ duration: 0.6, delay: 0.2 }}
              >
                <Lightbulb className="w-16 h-16 md:w-20 md:h-20 text-yellow-300 mx-auto mb-3 drop-shadow-lg" />
              </motion.div>
              <h3 className="text-xl md:text-2xl font-black text-white mb-1">Feynman Method</h3>
              <p className="text-purple-100 text-xs md:text-sm">Explain it simply to truly understand it</p>
            </div>
            <div className="p-5 md:p-6 text-center">
              <p className={`mb-5 leading-relaxed text-sm md:text-base ${isDark ? 'text-slate-300' : 'text-slate-600'}`}>
                Explain concepts in your own words and get instant AI feedback on your understanding.
              </p>
              <Button
                onClick={() => generateCards()}
                className="w-full h-12 md:h-14 bg-gradient-to-r from-purple-600 via-purple-700 to-purple-800 hover:from-purple-700 hover:via-purple-800 hover:to-purple-900 text-white font-bold text-base md:text-lg rounded-xl shadow-xl"
              >
                <Sparkles className="w-5 h-5 mr-2" />
                Generate Cards
              </Button>
              <button
                onClick={() => setShowCustomize(true)}
                className={`w-full mt-2 text-sm font-medium py-2 rounded-lg transition-colors ${isDark ? 'text-purple-400 hover:bg-purple-500/10' : 'text-purple-600 hover:bg-purple-50'}`}
              >
                ⚙️ Customize (topics, difficulty, amount)
              </button>
              <CustomizeGenerationModal
                open={showCustomize}
                onOpenChange={setShowCustomize}
                type="teach_it"
                lessonId={lesson?.id}
                compressedContent={lesson?.compressed_content || extractedContent}
                onGenerate={(opts) => generateCards(opts)}
              />
            </div>
          </Card>
        </motion.div>
      </div>
    );
  }

  // Compute set-scoped indices for navigation
  const setIndices = currentSetCardIds
    ? cards.map((c, i) => currentSetCardIds.includes(c.id) ? i : -1).filter(i => i >= 0)
    : cards.map((_, i) => i);
  const posInSet = setIndices.indexOf(currentCardIndex);
  const setSize = setIndices.length;
  const currentCard = cards[currentCardIndex];
  const progress = setSize > 0 ? ((posInSet + 1) / setSize) * 100 : 0;
  const setCompletedCount = setIndices.filter(i => cards[i]?.completed).length;
  const FREE_TEACHIT_LIMIT = 1; // Free users can interact with 1 card per set
  const isCardLocked = !isPro() && posInSet >= FREE_TEACHIT_LIMIT && !currentCard.completed;

  return (
    <div ref={tabContainerRef} className={`relative flex flex-col w-full max-w-full pb-8 ${isDark ? 'bg-[#0a0a12]' : 'bg-slate-50'}`} style={{ boxSizing: 'border-box', overflowX: 'hidden' }}>
      {/* XP Toast - positioned within this container */}
      <AnimatePresence>
        {xpToast.show && (
          <motion.div
            initial={{ opacity: 0, scale: 0.7, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.7, y: -20 }}
            transition={{ type: "spring", stiffness: 400, damping: 25 }}
            className="absolute top-16 left-1/2 -translate-x-1/2 z-50 pointer-events-none"
            onAnimationComplete={() => {
              setTimeout(() => setXpToast({ show: false, xp: 0, reason: '' }), 1800);
            }}
          >
            <div className="bg-gradient-to-r from-yellow-400 to-amber-500 text-slate-900 px-5 py-3 rounded-2xl shadow-2xl flex items-center gap-2.5">
              <motion.span
                animate={{ rotate: [0, -15, 15, 0], scale: [1, 1.3, 1] }}
                transition={{ duration: 0.5 }}
                className="text-lg"
              >⚡</motion.span>
              <div>
                <p className="text-lg font-bold">+{xpToast.xp} XP</p>
                {xpToast.reason && <p className="text-xs text-slate-700">{xpToast.reason}</p>}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Sets List Modal */}
      <AnimatePresence>
        {showSetsList && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"
            onClick={() => setShowSetsList(false)}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className={`rounded-2xl max-w-sm w-full p-5 shadow-2xl max-h-[70vh] overflow-y-auto ${isDark ? 'bg-[#12121a]' : 'bg-white'}`}
              onClick={e => e.stopPropagation()}
            >
              <div className="flex items-center justify-between mb-4">
                <h3 className={`text-lg font-bold ${isDark ? 'text-slate-100' : 'text-slate-900'}`}>Feynman Sets</h3>
                <button onClick={() => setShowSetsList(false)} className={`p-1 rounded-full ${isDark ? 'hover:bg-white/10' : 'hover:bg-slate-100'}`}>
                  <X className="w-5 h-5 text-slate-500" />
                </button>
              </div>
              {(() => {
                const setMap = new Map();
                cards.forEach(card => {
                  const topic = card.topic || 'General Concepts';
                  if (!setMap.has(topic)) setMap.set(topic, { topic, cards: [], mastered: 0 });
                  const set = setMap.get(topic);
                  set.cards.push(card);
                  if (card.mastered) set.mastered++;
                });
                const sets = Array.from(setMap.values());
                return (
                  <div className="space-y-2">
                    {sets.map((set) => {
                      const prog = (set.mastered / set.cards.length) * 100;
                      return (
                        <button
                          key={set.topic}
                          onClick={() => {
                            const setCards = cards.filter(c => (c.topic || 'General Concepts') === set.topic);
                            const setCardIds = setCards.map(c => c.id);
                            const firstIdx = cards.findIndex(c => c.id === setCards[0]?.id);
                            if (firstIdx >= 0) {
                              setCurrentCardIndex(firstIdx);
                              setUserAnswer(cards[firstIdx].user_answer || "");
                              setShowFeedback(cards[firstIdx].completed);
                              setCurrentSetCardIds(setCardIds);
                            }
                            setShowSetsList(false);
                          }}
                          className={`w-full p-3 rounded-xl border transition-all text-left ${isDark ? 'bg-white/5 hover:bg-purple-600/20 border-white/10 hover:border-purple-500/30' : 'bg-slate-50 hover:bg-purple-50 border-slate-200 hover:border-purple-300'}`}
                        >
                          <div className="flex items-center justify-between mb-2">
                            <span className={`font-semibold text-sm ${isDark ? 'text-slate-100' : 'text-slate-900'}`}>{set.topic}</span>
                            <span className={`text-xs ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>{set.mastered}/{set.cards.length}</span>
                          </div>
                          <div className={`h-1.5 rounded-full overflow-hidden ${isDark ? 'bg-white/10' : 'bg-slate-200'}`}>
                            <div className="h-full bg-gradient-to-r from-violet-500 to-purple-600 rounded-full" style={{ width: `${prog}%` }} />
                          </div>
                        </button>
                      );
                    })}
                  </div>
                );
              })()}
              <Button onClick={() => { setShowSetsList(false); handleRegenerate(); }} variant="outline" className="w-full mt-4">
                <RefreshCw className="w-3.5 h-3.5 mr-2" /> Generate New Set
              </Button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Colorful top bar */}
      <div className="bg-gradient-to-r from-purple-600 via-indigo-600 to-purple-700 px-3 py-2.5 md:px-4 flex items-center justify-between relative">
        <button
          onClick={() => setShowSetsList(true)}
          className="flex items-center gap-1 text-xs font-medium px-2.5 py-1.5 rounded-lg transition-colors text-white/80 bg-white/15 hover:bg-white/25"
        >
          <X className="w-3 h-3" />
          Back
        </button>
        {/* Centered counter */}
        <div className="absolute left-1/2 -translate-x-1/2 flex items-center gap-2">
          <span className="text-sm font-bold text-white">
            {posInSet + 1} / {setSize}
          </span>
          <span className="text-xs text-white/50">•</span>
          <span className="text-xs text-white/70">{setCompletedCount} done</span>
        </div>
        <Button
          variant="ghost"
          size="sm"
          onClick={handleRegenerate}
          className="gap-1 h-7 px-2 text-white/80 hover:text-white hover:bg-white/15"
        >
          <RefreshCw className="w-3 h-3" />
          <span className="hidden sm:inline text-xs">New</span>
        </Button>
      </div>

      {/* Progress Bar */}
      <div className="px-3 md:px-4 pt-2">
        <div className={`h-1.5 rounded-full overflow-hidden ${isDark ? 'bg-white/10' : 'bg-purple-100'}`}>
          <motion.div
            className="h-full bg-gradient-to-r from-purple-500 to-indigo-500"
            initial={{ width: 0 }}
            animate={{ width: `${progress}%` }}
            transition={{ duration: 0.3, ease: "easeOut" }}
          />
        </div>
      </div>

      {/* Card content */}
      <div className="px-3 py-3 md:px-4 w-full max-w-full flex items-start justify-center" style={{ boxSizing: 'border-box' }}>
        <AnimatePresence mode="wait">
          <motion.div
            key={currentCardIndex}
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.95 }}
            transition={{ duration: 0.25 }}
            className="w-full max-w-full"
            style={{ boxSizing: 'border-box' }}
          >
            <Card className={`backdrop-blur-xl border shadow-xl overflow-hidden w-full max-w-full ${isDark ? 'bg-[#12121a]/95 border-purple-500/30' : 'bg-white/95 border-purple-200/50'}`} style={{ boxSizing: 'border-box' }}>
              {/* Question Area */}
              <div className={`px-4 py-5 md:px-6 md:py-6 w-full ${isDark ? 'bg-gradient-to-br from-purple-900/40 to-indigo-900/40' : 'bg-gradient-to-br from-purple-50 to-indigo-50'}`}>
                <div className="flex items-center justify-center text-center mb-3">
                  <MathText className={`text-lg md:text-xl font-bold leading-relaxed break-words ${isDark ? 'text-white' : 'text-slate-900'}`}>
                    {currentCard.question}
                  </MathText>
                </div>
                {/* AskAI button centered below question */}
                <div className="flex justify-center" onClick={(e) => e.stopPropagation()}>
                  <AskAIButton 
                    type="teachit" 
                    data={{ question: currentCard.question, model_answer: currentCard.model_answer }} 
                    lesson={lesson} 
                    size="sm" 
                  />
                </div>
              </div>

              <div className="p-4 md:p-6 w-full">
                {!showFeedback ? (
                  isCardLocked ? (
                    <LockedTeachItInput />
                  ) : (
                  <>
                    <Textarea
                      value={userAnswer}
                      onChange={(e) => setUserAnswer(e.target.value)}
                      placeholder="Type or dictate your explanation..."
                      className="min-h-[140px] md:min-h-[200px] mb-3 text-sm md:text-base border-2 border-purple-200 focus:border-purple-400 rounded-xl resize-none w-full"
                      disabled={isGrading}
                    />
                    
                    <Button
                      onClick={gradeAnswer}
                      disabled={!userAnswer.trim() || isGrading}
                      className="w-full h-11 md:h-14 bg-gradient-to-r from-purple-600 via-purple-700 to-purple-800 hover:from-purple-700 hover:via-purple-800 hover:to-purple-900 text-white font-semibold rounded-xl shadow-lg text-sm md:text-lg"
                    >
                      {isGrading ? (
                        <><Loader2 className="w-4 h-4 md:w-5 md:h-5 mr-2 animate-spin" /> Submitted! AI is grading...</>
                      ) : (
                        <><CheckCircle2 className="w-4 h-4 md:w-5 md:h-5 mr-2" /> Submit</>
                      )}
                    </Button>
                  </>
                  )
                ) : (
                  <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.2 }} className="space-y-2 md:space-y-4 w-full">
                    {/* Score Badge */}
                    <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} transition={{ type: "spring", delay: 0.3 }} className="flex items-center justify-center">
                      <div className={`px-5 py-2 md:px-8 md:py-4 rounded-2xl ${
                        currentCard.score >= 90 ? 'bg-gradient-to-r from-emerald-500 to-green-600' :
                        currentCard.score >= 75 ? 'bg-gradient-to-r from-purple-500 to-indigo-600' :
                        currentCard.score >= 60 ? 'bg-gradient-to-r from-yellow-500 to-orange-600' :
                        'bg-gradient-to-r from-red-500 to-pink-600'
                      } shadow-xl`}>
                        <p className="text-white/80 text-[10px] md:text-xs font-medium text-center">Your Score</p>
                        <p className="text-white text-2xl md:text-4xl font-black text-center">{currentCard.score}<span className="text-base md:text-2xl">/100</span></p>
                      </div>
                    </motion.div>

                    {/* Your Answer */}
                    <div className={`border rounded-xl p-3 md:p-4 w-full ${isDark ? 'bg-white/5 border-white/10' : 'bg-slate-50 border-slate-200'}`}>
                      <h4 className={`font-semibold mb-1.5 flex items-center gap-1.5 text-xs md:text-sm ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>
                        <PenLine className={`w-3.5 h-3.5 md:w-4 md:h-4 ${isDark ? 'text-slate-400' : 'text-slate-500'}`} /> Your Answer
                      </h4>
                      <p className={`text-xs md:text-sm leading-relaxed ${isDark ? 'text-slate-300' : 'text-slate-600'}`}>{currentCard.user_answer}</p>
                    </div>

                    {/* Strengths */}
                    {currentCard.strengths?.length > 0 && (
                      <div className={`border rounded-xl p-3 md:p-4 w-full ${isDark ? 'bg-emerald-500/10 border-emerald-500/30' : 'bg-emerald-50 border-emerald-200'}`}>
                        <h4 className={`font-semibold mb-1.5 flex items-center gap-1.5 text-xs md:text-sm ${isDark ? 'text-emerald-400' : 'text-emerald-800'}`}>
                          <CheckCircle2 className="w-3.5 h-3.5 md:w-4 md:h-4 text-emerald-600" /> What You Did Well
                        </h4>
                        <ul className="space-y-1 md:space-y-1.5">
                          {currentCard.strengths.map((strength, idx) => (
                            <motion.li key={idx} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.4 + idx * 0.1 }}
                              className={`flex items-start gap-2 text-xs md:text-sm ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>
                              <span className="text-emerald-500 mt-0.5">✓</span>
                              <span className="leading-relaxed">{strength}</span>
                            </motion.li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Gaps */}
                    {currentCard.gaps?.length > 0 && (
                      <div className={`border rounded-xl p-3 md:p-4 w-full ${isDark ? 'bg-amber-500/10 border-amber-500/30' : 'bg-amber-50 border-amber-200'}`}>
                        <h4 className={`font-semibold mb-1.5 flex items-center gap-1.5 text-xs md:text-sm ${isDark ? 'text-amber-400' : 'text-amber-800'}`}>
                          <AlertCircle className="w-3.5 h-3.5 md:w-4 md:h-4 text-amber-600" /> To Review
                        </h4>
                        <ul className="space-y-1 md:space-y-1.5">
                          {currentCard.gaps.map((gap, idx) => (
                            <motion.li key={idx} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.5 + idx * 0.1 }}
                              className={`flex items-start gap-2 text-xs md:text-sm ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>
                              <span className="text-amber-500 mt-0.5">→</span>
                              <span className="leading-relaxed">{gap}</span>
                            </motion.li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Correct Answer */}
                    <div className={`border rounded-xl p-3 md:p-4 w-full ${isDark ? 'bg-gradient-to-br from-indigo-500/10 to-purple-500/10 border-indigo-500/30' : 'bg-gradient-to-br from-indigo-50 to-purple-50 border-indigo-200'}`}>
                      <h4 className={`font-semibold mb-1.5 flex items-center gap-1.5 text-xs md:text-sm ${isDark ? 'text-indigo-400' : 'text-indigo-800'}`}>
                        <Sparkles className={`w-3.5 h-3.5 md:w-4 md:h-4 ${isDark ? 'text-indigo-400' : 'text-indigo-600'}`} /> Correct Answer
                      </h4>
                      <MathText className={`text-xs md:text-sm leading-relaxed ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>{currentCard.model_answer}</MathText>
                    </div>

                    {/* Feedback */}
                    <div className={`border rounded-xl p-3 md:p-4 w-full ${isDark ? 'bg-purple-500/10 border-purple-500/30' : 'bg-purple-50 border-purple-200'}`}>
                      <h4 className={`font-semibold mb-1.5 flex items-center gap-1.5 text-xs md:text-sm ${isDark ? 'text-purple-400' : 'text-purple-800'}`}>
                        <Lightbulb className={`w-3.5 h-3.5 md:w-4 md:h-4 ${isDark ? 'text-purple-400' : 'text-purple-600'}`} /> AI Feedback
                      </h4>
                      <p className={`text-xs md:text-sm leading-relaxed ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>{currentCard.feedback}</p>
                    </div>
                  </motion.div>
                )}
              </div>
            </Card>
          </motion.div>
        </AnimatePresence>
      </div>

      {/* Navigation */}
      <div className={`backdrop-blur-xl border-t px-3 py-3 md:px-6 md:py-4 w-full ${isDark ? 'bg-[#12121a]/95 border-purple-500/30' : 'bg-white/95 border-purple-200'}`}>
        <div className="flex gap-3 w-full max-w-lg mx-auto">
          <Button
            variant="outline"
            onClick={handlePrevious}
            disabled={posInSet <= 0}
            className={`flex-1 h-10 md:h-12 rounded-xl border-2 disabled:opacity-30 font-semibold text-sm md:text-base ${isDark ? 'border-purple-500/30 hover:bg-purple-600/20 text-slate-200' : 'border-purple-300 hover:bg-purple-50 text-slate-900'}`}
          >
            Previous
          </Button>
          <Button
            onClick={handleNext}
            disabled={posInSet >= setSize - 1}
            className="flex-1 h-10 md:h-12 bg-gradient-to-r from-purple-600 to-purple-700 hover:from-purple-700 hover:to-purple-800 text-white rounded-xl shadow-lg disabled:opacity-30 font-semibold text-sm md:text-base"
          >
            Next
          </Button>
        </div>
      </div>
    </div>
  );
}